### ISSUE TITLE
getting error while putting sftp credential

### ISSUE THREAD

**Issue by atulnetbeam** [Yenthe666/auto_backup#10]
i am getting this error.

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo1/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo1/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo1/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo1/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo1/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo1/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo1/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo1/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo1/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo1/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo1/addons/auto_backup/backup_scheduler.py", line 113, in test_sftp_connection
    db_list = self.get_db_list(cr, uid, [], rec.host, rec.port)
  File "/opt/odoo1/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo1/addons/auto_backup/backup_scheduler.py", line 57, in get_db_list
    db_list = execute(conn, 'list')
  File "/opt/odoo1/addons/auto_backup/backup_scheduler.py", line 46, in execute
    raise e
error: [Errno 111] Connection refused

**Comment by Yenthe666** [comment]
hi @atulnetbeam 

Could you share a bit more details about your configuration? Did the test connection button give this or? What have you configured? Can you provide me with a screenshot where you sensor out the password/username or something please? :+1:

**Comment by Yenthe666** [comment]
Closed since I had no response in three weeks. Feel free to comment if the problem still persist or you can create a new issue!
