### ISSUE TITLE
 No matching record found for external id 'model_db_backup' in field 'Object' error

### ISSUE THREAD

**Issue by MohsenWaleed** [Yenthe666/auto_backup#105]
Tried to install it but got the below error :

Traceback (most recent call last):
  File "C:\odoo\odoo-11.0_Test\odoo\http.py", line 647, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\odoo\odoo-11.0_Test\odoo\http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\odoo\odoo-11.0_Test\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\odoo\odoo-11.0_Test\odoo\http.py", line 689, in dispatch
    result = self._call_function(**self.params)
  File "C:\odoo\odoo-11.0_Test\odoo\http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\odoo\odoo-11.0_Test\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\odoo\odoo-11.0_Test\odoo\http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\odoo\odoo-11.0_Test\odoo\http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "C:\odoo\odoo-11.0_Test\odoo\http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "C:\odoo\odoo-11.0_Test\addons\web\controllers\main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "C:\odoo\odoo-11.0_Test\addons\web\controllers\main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\odoo\odoo-11.0_Test\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\odoo\odoo-11.0_Test\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "C:\odoo\odoo-11.0_Test\odoo\addons\base\module\module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\odoo\odoo-11.0_Test\odoo\addons\base\module\module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\odoo\odoo-11.0_Test\odoo\addons\base\module\module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\odoo\odoo-11.0_Test\odoo\modules\registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\odoo\odoo-11.0_Test\odoo\modules\loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "C:\odoo\odoo-11.0_Test\odoo\modules\loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "C:\odoo\odoo-11.0_Test\odoo\modules\loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "C:\odoo\odoo-11.0_Test\odoo\modules\loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "C:\odoo\odoo-11.0_Test\odoo\tools\convert.py", line 782, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "C:\odoo\odoo-11.0_Test\odoo\tools\convert.py", line 829, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading auto_backup failed: file auto_backup\security/ir.model.access.csv could not be processed:
 No matching record found for external id 'model_db_backup' in field 'Object'
Missing required value for the field 'Object' (model_id)
No matching record found for external id 'model_db_backup' in field 'Object'
Missing required value for the field 'Object' (model_id)

**Comment by MohsenWaleed** [comment]
Restart my machine solved the issue.
