### ISSUE TITLE
Multiple errors I cannot get around...

### ISSUE THREAD

**Issue by deejayalbatros** [Yenthe666/auto_backup#110]
@Yenthe666 as promised here is my feedback.

I'm using Odoo 10 on a laptop with Windows 10 x64. This is for test purposes as I will change to linux environment later when this is sorted.

I really want to use your plugin for automatic backups but I cannot get it to work. 

First of all, If I copy the plugin (auto_backup-10.0.10.0) to my addons folder (C:\Program Files (x86)\Odoo 10.0\server\odoo\addons) and restart my system I get an empty Odoo interface as described here: https://github.com/Yenthe666/auto_backup/issues/96

![image](https://user-images.githubusercontent.com/16037565/45941563-f2c3f500-c008-11e8-99b9-4ba2ee035945.png)

I know the github link describes the problem for version 11 but the same happens in version 10. When I remove the plugin from the plugins folder, restart the server the interface works again. If I then past the plugin into the addons folder again without rebooting but instead refresh the apps folder from within Odoo the plugin comes visible (without logo though). If I then press install from there I get the following error:

**Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 642, in _handle_exception
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 684, in dispatch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 334, in _call_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\model.py", line 101, in wrapper
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 327, in checked_call
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 942, in __call__
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 507, in response_wrap
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 899, in call_button
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 887, in _call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 689, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 680, in call_kw_multi
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\base\module\module.py", line 412, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\base\module\module.py", line 486, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\registry.py", line 83, in new
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\loading.py", line 377, in load_modules
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\loading.py", line 270, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\loading.py", line 182, in load_module_graph
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\loading.py", line 96, in _load_data
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 845, in convert_file
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 915, in convert_xml_import
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 796, in parse
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 799, in parse
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 707, in _tag_record
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\base\ir\ir_model.py", line 1238, in _update
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\base\ir\ir_ui_view.py", line 362, in create
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 3854, in create
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\fields.py", line 1046, in determine_inverse
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\base\ir\ir_ui_view.py", line 220, in _inverse_arch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\base\ir\ir_ui_view.py", line 380, in write
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 3567, in write
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 3731, in _write
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 1081, in _validate_fields
ParseError: "Error while validating constraint

Model not found: db.backup

Error context:
View `Configure Backup`
[view_id: 1070, xml_id: n/a, model: db.backup, parent_id: n/a]
None" while parsing file:///c:/program%20files%20(x86)/odoo%2010.0/server/odoo/addons/auto_backup/views/bkp_conf_view.xml:4, near
<record model="ir.ui.view" id="view_backup_conf_form">
      <field name="name">Configure Backup</field>
      <field name="model">db.backup</field>
      <field name="type">form</field>
      <field name="arch" type="xml">
        <form string="Test">
	  <group col="4" colspan="4">
	    <separator col="2" string="Local backup configuration"/>
          </group>
	  <group>
	    <field name="host" colspan="2"/>
	    <field name="name"/>
	    <field name="port"/>
	    <field name="backup_type"/>
	    <field name="folder"/>
	    <field name="autoremove"/>
	    <field name="days_to_keep" attrs="{'invisible': [('autoremove','=',False)]}"/>
	  </group>
	  <group col="4" colspan="4">
	    <separator col="2" string="SFTP"/>
          </group>
          <div style="width:50%;border-radius:10px;margin: 10px 0px;padding:15px 10px 15px 10px; background-repeat: no-repeat;background-position: 10px center;color: #9F6000;background-color: #FEEFB3;" attrs="{'invisible': [('sftp_write','=',False)]}"><b>Warning:</b> Use SFTP with caution! This writes files to external servers under the path you specify.</div>
	    <group>
              <field name="sftp_write"/>
              <field name="sftp_host" attrs="{'invisible':[('sftp_write', '=', False)],'required':[('sftp_write', '=', True)]}"/>
              <field name="sftp_port" attrs="{'invisible':[('sftp_write', '=', False)],'required':[('sftp_write', '=', True)]}"/>
              <field name="sftp_user" attrs="{'invisible':[('sftp_write', '=', False)], 'required':[('sftp_write', '=', True)]}"/>
              <field name="sftp_password" attrs="{'invisible':[('sftp_write', '=', False)],'required': [('sftp_write', '=', True)]}" password="True"/>
              <field name="sftp_path" attrs="{'invisible':[('sftp_write', '==', False)],'required':[('sftp_write', '==', True)]}" placeholder="For example: /odoo/backups/"/>
              <field name="days_to_keep_sftp" attrs="{'invisible': [('sftp_write', '=', False)], 'required': [('sftp_write', '=', True)]}"/>
              <field name="send_mail_sftp_fail" attrs="{'invisible': [('sftp_write','=',False)]}"/>
	      <field name="email_to_notify" attrs="{'invisible':['|',('send_mail_sftp_fail', '==', False), ('sftp_write', '=', False)], 'required': [('send_mail_sftp_fail', '=', True)]}"/>
              <button name="test_sftp_connection" type="object" attrs="{'invisible': [('sftp_write','=',False)]}" string="Test SFTP Connection" icon="gtk-network"/>
            </group>
            <separator string="Help" colspan="2"/>
            <div>
              This configures the scheduler for automatic backup of the given database running on given host at given port on regular intervals.
              <br/>
	      Automatic backups of the database can be scheduled as follows: 
	      <ol>
		<li>
		  Go to Settings / Technical / Automation / Scheduled Actions.
		</li>
		<li>
		  Search the action named 'Backup scheduler'.
		</li>
		<li>
		  Set the scheduler to active and fill in how often you want backups generated.
		</li>
              </ol>
	      <p style="font-size:18px;">
		Need more help? <a href="mailto:yenthe.vanginneken@vanroey.be">Contact us!</a>
	      </p>
	  </div>
        </form>
      </field>
    </record>**

If I then try the solution on the bottom of this page: https://github.com/Yenthe666/auto_backup/issues/65

I get the following: 

![image](https://user-images.githubusercontent.com/16037565/45941634-5c440380-c009-11e8-8ab5-7f6ca24ba913.png)

And also: 

![image](https://user-images.githubusercontent.com/16037565/45941645-67972f00-c009-11e8-867d-4a40555b05a4.png)
![image](https://user-images.githubusercontent.com/16037565/45941653-6f56d380-c009-11e8-805b-00cc7262ff2b.png)

So I think everything is installed, what can be the problem here??

PS If you need any logs and are willing to tell me how to get them there is no problem providing them...

**Comment by Yenthe666** [comment]
Hmm, odd this looks okay. I've never personally tried it on Windows though, maybe I should add a warning in the module.
What is the output of the odoo logfile after you add it to the list of modules? I believe it should be under c:\Program Files\Odoo

**Comment by deejayalbatros** [comment]
[odoolog.txt](https://github.com/Yenthe666/auto_backup/files/2410060/odoolog.txt)

**Comment by Yenthe666** [comment]
The real error seems to come from this part:
```
2018-09-24 08:02:13,719 1068 ERROR PSMOTOR odoo.service.server: Exception happened during processing of request from ('127.0.0.1', 53416)
Traceback (most recent call last):
  File "SocketServer.pyc", line 599, in process_request_thread
  File "SocketServer.pyc", line 334, in finish_request
  File "SocketServer.pyc", line 657, in __init__
  File "SocketServer.pyc", line 716, in finish
  File "socket.pyc", line 283, in close
  File "socket.pyc", line 307, in flush
error: [Errno 10053] An established connection was aborted by the software in your host machine
```

It looks like a more common problem on Windows computers with P2:
https://stackoverflow.com/questions/17854713/error-errno-10053
https://stackoverflow.com/questions/40247025/flask-socket-error-errno-10053-an-established-connection-was-aborted-by-the/40257165

You might want to try one of those options to get it going but it is not related to my Odoo module itself. Sadly it is the package I use.

**Comment by deejayalbatros** [comment]
Ok thanks for investigating. I remember I had the same issue in Linux but I
will check that again first before complaining :) Odoo V10 doesn't support
Python 3 I guess?

**Comment by Yenthe666** [comment]
You're welcome! And indeed, it doesn't support P3 out of the box. On Linux it should all work fine, I've got multiple Odoo's running with my module on Linux. 😄
