### ISSUE TITLE
Backup doesn't run

### ISSUE THREAD

**Issue by deejayalbatros** [Yenthe666/auto_backup#112]
Configuration:

![image](https://user-images.githubusercontent.com/16037565/46065817-5121dc80-c19d-11e8-9500-66eab08e3911.png)

![image](https://user-images.githubusercontent.com/16037565/46065828-5bdc7180-c19d-11e8-8fda-b896112bc6bb.png)

![image](https://user-images.githubusercontent.com/16037565/46065835-6139bc00-c19d-11e8-9ee3-dbdbad3730eb.png)

![image](https://user-images.githubusercontent.com/16037565/46065877-7e6e8a80-c19d-11e8-8cee-7336bf2007f7.png)

![image](https://user-images.githubusercontent.com/16037565/46065926-9b0ac280-c19d-11e8-93f5-defc7883b947.png)

Backups aren't saved, I cannot see the problem though...

**Comment by Yenthe666** [comment]
@deejayalbatros have a look in the logfiles & paste it here please. I assume a rights issue on the folder or an invalid path.

**Comment by deejayalbatros** [comment]
2018-09-26 09:03:32,270 1192 INFO None werkzeug: 127.0.0.1 - - [26/Sep/2018 09:03:32] "POST /xmlrpc/db HTTP/1.1" 200 -
2018-09-26 09:03:32,278 1192 INFO PSMOTOR requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): localhost
2018-09-26 09:03:32,301 1192 INFO PSMOTOR odoo.service.db: DUMP DB: PSMOTOR format zip
2018-09-26 09:03:37,466 1192 INFO PSMOTOR werkzeug: 127.0.0.1 - - [26/Sep/2018 09:03:37] "POST /web/database/backup HTTP/1.1" 200 -
2018-09-26 09:03:37,473 1192 ERROR PSMOTOR odoo.addons.base.ir.ir_cron: Call of self.env[u'db.backup'].schedule_backup(*()) failed in Job #7
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_cron.py", line 126, in _callback
    getattr(model, method_name)(*args)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/auto_backup/models/db_backup.py", line 165, in schedule_backup
    with open(file_path,'wb') as fp:
IOError: [Errno 13] Permission denied: u'/home/janick/Downloads/backups/26_09_2018_09_03_32_PSMOTOR.zip'
2018-09-26 09:03:37,481 1192 INFO PSMOTOR werkzeug: 127.0.0.1 - - [26/Sep/2018 09:03:37] "POST /web/dataset/call_button HTTP/1.1" 200 -
2018-09-26 09:03:37,630 1192 INFO PSMOTOR werkzeug: 127.0.0.1 - - [26/Sep/2018 09:03:37] "POST /web/menu/load_needaction HTTP/1.1" 200 -
2018-09-26 09:03:37,649 1192 INFO PSMOTOR werkzeug: 127.0.0.1 - - [26/Sep/2018 09:03:37] "POST /web/dataset/call_kw/ir.cron/search_read HTTP/1.1" 200 -
2018-09-26 09:03:37,746 1192 INFO PSMOTOR werkzeug: 127.0.0.1 - - [26/Sep/2018 09:03:37] "POST /web/dataset/search_read HTTP/1.1" 200 -
2018-09-26 09:03:47,792 1192 INFO PSMOTOR werkzeug: 127.0.0.1 - - [26/Sep/2018 09:03:47] "POST /longpolling/poll HTTP/1.1" 200 -


Why is permission denied in the home folder?

**Comment by Yenthe666** [comment]
Not enough rights for the user running Odoo to create files in that folder. This user needs the ability to create and write files on the /backups folder.

**Comment by deejayalbatros** [comment]
chmod on backup folder?

**Comment by Yenthe666** [comment]
Exactly!

**Comment by deejayalbatros** [comment]
after chmod 755 on /home/janick/Downloads/backups the error changes to permission denied in /home/janick/Downloads

chmod on Downloads doesn't work

**Comment by Yenthe666** [comment]
Do a sudo chmod -R 777 on `/home/janick/Downloads` just to try if it works then. Change afterwards accordingly if it works.

**Comment by deejayalbatros** [comment]
chmod -R 777 on Downloads folder finally works! Backups are created. Should I leave it like that or are there security issues? I'm not sure what you mean by "Change afterwards accordingly if it works."

**Comment by Yenthe666** [comment]
Basically you've now given every single user on the sytem full rights on the Downloads folders and all folders in there. That can be considered a security threat.
Now just set enough rights for your Odoo user instead of for all users and it'll work just fine.
