### ISSUE TITLE
I cant install the module 

### ISSUE THREAD

**Issue by instechMX** [Yenthe666/auto_backup#134]
I try comment the line  "#import paramiko" and I receive the below error. I disable the /web/database/manager page for security.  
Thanks in advance.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 797, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 844, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Fallo en la carga del módulo auto_backup: no se pudo procesar el archivo auto_backup/security/ir.model.access.csv:
No se han encontrado registros coincidentes para id. externo 'model_db_backup' en el campo 'Object'
No se han encontrado registros coincidentes para id. externo 'model_db_backup' en el campo 'Object'
Falta el valor requerido para el campo 'Object' (model_id)
Falta el valor requerido para el campo 'Object' (model_id)

**Comment by Yenthe666** [comment]
@instechMX I've had a few of these reports through the years but I was never able to identify this issue. You say that you've disabled the /web/database/manager page.. what happens if you enable it? Does the module still complain then?

**Comment by instechMX** [comment]
I already enebla ir and its working now, Just few problems with the local backup

**Comment by Yenthe666** [comment]
So you can confirm that it does not work if your manager is disabled and that it does work if the manager is enabled? How exactly did you disable the manager? You're the first one in years that seems to have found it. :)

**Comment by instechMX** [comment]
in de oddo.conf you had to change the "list database" parameter to False, or you can use this module/app "https://apps.odoo.com/apps/modules/12.0/oi_stop_database_manager/"
I'm disabling this supposedly for security. Because anybody can access to the database manager. Unfortunlenty this disable the URL web/database/manager for localhost, So your module can´t make the backup.

**Comment by Yenthe666** [comment]
Yes, it relies on a function that is related to the database manager caller. There is no easy solution around it sadly..
So because of it being disabled you where not able to backup and got the traceback you first reported, right?

**Comment by instechMX** [comment]
Yes, That's why its failing

**Comment by Yenthe666** [comment]
Alright thanks a lot for the feedback. I'm happy I finally know what it is and I'll document it as soon as possible.

**Comment by Yenthe666** [comment]
It was documented at https://github.com/Yenthe666/auto_backup/commit/f2ea02d1e433dbf3898d5382ace9485db629666e - just forgot to reference it here.
