### ISSUE TITLE
error backup odoo 12

### ISSUE THREAD

**Issue by hugo49** [Yenthe666/auto_backup#135]
From the web page http: // ******: 8069 / web / database / backup. It is impossible to make a backup with zip inclued filestore, only the dump works. 

Here is the message: Database backup error: Can not close the file while there is an open handle on it. Close the writing handle before closing the zip.

No logs for backups.

Only the dropbox module for automatic backups tells me this message: Exception: Can't close the ZIP file while there is an open writing handle on it. Close the writing handle before closing the zip.

I tried to backup the database only. it is downloading, but it is not good because it can not be restored to another odoo instance.

Database Restore Error: Postgres Subprocess ('/ usr / bin / pg_restore', '--dbname = mabase', '--no-owner', '/ tmp / tmpcfuie_tn') error 1 and after 500: Internal server error

**Comment by Yenthe666** [comment]
@hugo49 you have not correctly configured the database user on this database and you should also update your Odoo instance. There has also been a bug a whole while back regarding backups being closed too soon.

**Comment by hugo49** [comment]
you have not correctly configured the database user on this database.
What should I do exactly?

Here are some logs.
2019-06-14 14:44:47,753 14501 INFO ? odoo.service.server: Thread <Thread(odoo.service.cron.cron0, started daemon 140416756868864)> virtual real time limit (164/120s) reached.
2019-06-14 14:44:47,754 14501 INFO ? odoo.service.server: Thread <Thread(odoo.service.http.request.140416454735616, started 140416454735616)> virtual real time limit (120/120s) reached.
2019-06-14 14:44:49,449 14501 INFO ? odoo: Odoo version 12.0-20190614
2019-06-14 14:44:49,451 14501 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2019-06-14 14:44:49,451 14501 INFO ? odoo: addons paths: ['/var/lib/odoo/.local/share/Odoo/addons/12.0', '/usr/lib/python3/dist-packages/odoo/addons']
2019-06-14 14:44:49,452 14501 INFO ? odoo: database: odoo@default:default
2019-06-14 14:44:49,701 14501 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2019-06-14 14:44:49,949 14501 WARNING ? odoo.addons.base.models.res_currency: The num2words python library is not installed, amount-to-text features won't be fully available.
2019-06-14 14:44:49,994 14501 INFO ? odoo.service.server: HTTP service (werkzeug) running on mon-ip.info:8069

**Comment by Yenthe666** [comment]
Make sure that your db is set to the Odoo user and that everything matches. Update your Odoo instance to the latest source code and then see if you can take a backup through /web/database/manager.

**Comment by sswapnesh** [comment]
@hugo49 
`
Thread <Thread(odoo.service.cron.cron0, started daemon 140416756868864)> virtual real time limit (164/120s) reached.`

Increase virtual real time limit in odoo.conf

**Comment by Yenthe666** [comment]
Good catch too yes.

**Comment by FnetOdoo** [comment]
2024-08-23 08:47:35,800 590119 ERROR ? odoo.addons.web.controllers.main: Database.backup
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/zipfile.py", line 1646, in write
    shutil.copyfileobj(src, dest, 1024*8)
  File "/usr/local/lib/python3.6/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
  File "/usr/local/lib/python3.6/zipfile.py", line 1015, in write
    self._fileobj.write(data)
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fnet/odoo11/odoo-server/odoo/tools/osutil.py", line 78, in zip_dir
    zipf.write(path, path[len_prefix:])
  File "/usr/local/lib/python3.6/zipfile.py", line 1646, in write
    shutil.copyfileobj(src, dest, 1024*8)
  File "/usr/local/lib/python3.6/zipfile.py", line 1053, in close
    self._fileobj.seek(self._zinfo.header_offset)
**OSError: [Errno 28] No space left on device**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fnet/odoo11/odoo-server/addons/web/controllers/main.py", line 736, in backup
    dump_stream = odoo.service.db.dump_db(name, None, backup_format)
  File "/home/fnet/odoo11/custom/fms_gfms/custom/gfms_addons/automatic_backup/models/automatic_backup.py", line 121, in dump_db
    odoo.tools.osutil.zip_dir(dump_dir, t, include_dir=False, fnct_sort=lambda file_name: file_name != 'dump.sql')
  File "/home/fnet/odoo11/odoo-server/odoo/tools/osutil.py", line 78, in zip_dir
    zipf.write(path, path[len_prefix:])
  File "/usr/local/lib/python3.6/zipfile.py", line 1174, in __exit__
    self.close()
  File "/usr/local/lib/python3.6/zipfile.py", line 1695, in close
    raise ValueError("Can't close the ZIP file while there is "
ValueError: Can't close the ZIP file while there is an open writing handle on it. Close the writing handle before closing the zip.
Exception ignored in: <bound method ZipFile.__del__ of <zipfile.ZipFile file=<_io.BufferedRandom name=5> mode='w'>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/zipfile.py", line 1686, in __del__
    self.close()
  File "/usr/local/lib/python3.6/zipfile.py", line 1695, in close
    raise ValueError("Can't close the ZIP file while there is "
ValueError: Can't close the ZIP file while there is an open writing handle on it. Close the writing handle before closing the zip.


**It is due to the storage. Check your available space on the machine.**
