### ISSUE TITLE
Cant Install on Odoo v12

### ISSUE THREAD

**Issue by josu22** [Yenthe666/auto_backup#139]
I tried unzipping from odoo/apps and clonning repository.

Nothing works. Allways the same error :(

```
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo/odoo-server/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 798, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 845, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Fallo en la carga del módulo auto_backup: no se pudo procesar el archivo auto_backup/security/ir.model.access.csv:
No se han encontrado registros coincidentes para id. externo 'model_db_backup' en el campo 'Object'
No se han encontrado registros coincidentes para id. externo 'model_db_backup' en el campo 'Object'
Falta el valor requerido para el campo 'Object' (model_id)
Falta el valor requerido para el campo 'Object' (model_id)
```

**Comment by Yenthe666** [comment]
You can actually see it is there (https://github.com/Yenthe666/auto_backup/blob/12.0/auto_backup/security/ir.model.access.csv)
There are multiple tickets regarding this but nobody was ever able to answer me what was different or wrong. See https://github.com/Yenthe666/auto_backup/issues/136
https://github.com/Yenthe666/auto_backup/issues/105
https://github.com/Yenthe666/auto_backup/issues/119
https://github.com/Yenthe666/auto_backup/issues/129
https://github.com/Yenthe666/auto_backup/issues/130

As long as nobody gives me reproducible steps for the issue I cannot help. I have dozens of servers running with this module fine so it has to be something locally.

Regards,
Yenthe

**Comment by Yenthe666** [comment]
Have you also checked all of the important info parts?
https://github.com/Yenthe666/auto_backup#4-important-information

**Comment by josu22** [comment]
After configure SSL on Odoo works fine.
