### ISSUE TITLE
Error Menu does not appears

### ISSUE THREAD

**Issue by mm82299** [Yenthe666/auto_backup#150]
Hello,
I have download the auto_backup module and tried to install it on Odoo 11, i tried the following steps:
copied the module under the addons folder.
Restart odoo server.
Clear browser cache.
but when logging to odoo, the main menu does not appears
Any Idea?
Thanks in advance

**Comment by Yenthe666** [comment]
Are you sure that your user has rights on this model though? ;)

**Comment by mm82299** [comment]
Hello,
I'm using odoo 11 in windows 10 environment

**Comment by mm82299** [comment]
Hello,
I have the same issue on Ubuntu 18.04, the module does not appears
Any idea ?

Thanks,
Mourad

**Comment by Yenthe666** [comment]
Again, "Are you sure that your user has rights on this model though? ;)"

**Comment by mm82299** [comment]
I was able to see the module after adding the rights but i got this error message when i tried to install it:
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 699, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 690, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 552, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo/odoo-server/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/odoo/odoo-server/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 784, in convert_file
    with file_open(pathname, 'rb') as fp:
  File "/odoo/odoo-server/odoo/tools/misc.py", line 198, in file_open
    return _fileopen(name, mode=mode, basedir=rtp, pathinfo=pathinfo, basename=basename)
  File "/odoo/odoo-server/odoo/tools/misc.py", line 256, in _fileopen
    raise IOError('File not found: %s' % basename)
OSError: File not found: auto_backup/security/user_groups.xml

**Comment by Yenthe666** [comment]
I've seen various reports with this issue but nobody was able to provide me a reproducible flow. It should work fine on Linux for sure. All reports seem to be Windows users so not sure.

**Comment by mm82299** [comment]
Hello,
I'm using Ubuntu 18.04 and Odoo11, i got this error message when installing the auto_backup module:
Exception: Impossible de charger le module auto_backup échec : fichier auto_backup/security/ir.model.access.csv :
Aucun enregistrement trouvé pour id externe 'model_db_backup' dans le champ 'Object'
Valeur requise manquante pour le champ 'Objet' (model_id)
Aucun enregistrement trouvé pour id externe 'model_db_backup' dans le champ 'Object'
Valeur requise manquante pour le champ 'Objet' (model_id)

**Comment by mm82299** [comment]
Hello,
Would you please send me a link to download the auto_backup module, seems that the one in Odoo apps is containing some updating that causing the issue when installing it

**Comment by Yenthe666** [comment]
? It's all available publicly in this repository
