### ISSUE TITLE
Error while installing autobackup module

### ISSUE THREAD

**Issue by CaptAnil** [Yenthe666/auto_backup#152]
I followed your instruction and installed and the following error occurred
I have installed paramiko and also  pysftp

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo12/odoo12-server/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo12/odoo12-server/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo12/odoo12-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo12/odoo12-server/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/odoo12/odoo12-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo12/odoo12-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo12/odoo12-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo12/odoo12-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo12/odoo12-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo12/odoo12-server/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo12/odoo12-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo12/odoo12-server/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo12/odoo12-server/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo12/odoo12-server/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo12/odoo12-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo12/odoo12-server/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo12/odoo12-server/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo12/odoo12-server/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/odoo12/odoo12-server/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/odoo12/odoo12-server/odoo/tools/convert.py", line 798, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/odoo12/odoo12-server/odoo/tools/convert.py", line 845, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading auto_backup failed: file auto_backup/security/ir.model.access.csv could not be processed:
 No matching record found for external id 'model_db_backup' in field 'Object'
No matching record found for external id 'model_db_backup' in field 'Object'
Missing required value for the field 'Object' (model_id)
Missing required value for the field 'Object' (model_id)

**Comment by CaptAnil** [comment]
solved , I was probably making some mistake with paramiko . I reinstalled paramiko  with pip3

**Comment by CaptAnil** [comment]
this got solved when I used pip3 to install paramiko
