### ISSUE TITLE
Update Module List Error

### ISSUE THREAD

**Issue by bridgeway04** [Yenthe666/auto_backup#16]
When I do "sudo pip install pysftp" on my Ubuntu server is says that pysftp is already installed?

ubuntu@ip-172-30-0-253:~$ sudo pip install pysftp
Requirement already satisfied (use --upgrade to upgrade): pysftp in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): paramiko>=1.7.7 in /usr/local/lib/python2.7/dist-packages (from pysftp)

I get the following error after I click Update Module List in Odoo: 

Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 393, in old_api
    result = new_api(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 397, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/wizard/base_module_update.py", line 15, in update_module
    self.updated, self.added = self.env['ir.module.module'].update_list()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 654, in update_list
    handler.load_addons()
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1298, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/auto_backup/__init__.py", line 23, in <module>
    import backup_scheduler
  File "/usr/lib/python2.7/dist-packages/openerp/addons/auto_backup/backup_scheduler.py", line 33, in <module>
    raise ImportError('This module needs pysftp to automaticly write backups to the FTP through SFTP. Please install pysftp on your system. (sudo pip install pysftp)')
ImportError: This module needs pysftp to automaticly write backups to the FTP through SFTP. Please install pysftp on your system. (sudo pip install pysftp)

Any idea?

**Comment by Yenthe666** [comment]
@bridgeway04,

Strange haven't had anybody with this issue yet. First try a reboot of your server.
If that doesn't work and If you don't use this module for anything else (I mean pysftp) I'd completely remove it and re-install it. There might be something wrong with the packages I guess.
If both of those do not work I'm not really sure since it is really there and it should work. I think the Odoo/services just aren't aware of the pysftp yet.

**Comment by bridgeway04** [comment]
Yenthe666,

When I reboot the server I get the following errors in the screenshot and I can't access the backend.  To bring the server backup, I remove the auto_backup folder from the addons directory and restart the server.  How do I safely remove the pysftp package and reinstall it using pip?

Brad

![auto_backup-error](https://cloud.githubusercontent.com/assets/12628174/10138256/8222d20c-65b2-11e5-9f04-af0461716bf0.png)

**Comment by Yenthe666** [comment]
@bridgeway04 

Restart your Odoo service and do a -u all, that will atleast fix your Odoo & backend.
For removing a package:
```pip uninstall [options] <package>```

**Comment by bridgeway04** [comment]
Thanks for the help! It seems that psyftp is no longer a default deb package and I had to install it myself and now the module is installed. 

I have set the configuration and scheduled the backup but it doesn't seem to be able to wright to my backup directory /home/ubuntu/backups/.  Are there special permissions that need to be set and for what user?

**Comment by Yenthe666** [comment]
@bridgeway04,

No problem! Strange that it wouldn't be a default deb package anymore.. I'll have a try at this soon too then. The user that runs the Odoo should have read and write access to the directory where the back-ups will be written to (so /home/ubuntu/backups/)

**Comment by bridgeway04** [comment]
Looks like I am getting closer but it just won't run?  Where do I change
the database administrator password?

Traceback (most recent call last):
  File
"/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_cron.py", line
138, in _callback
    getattr(model, method_name)(cr, uid, *args)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in
wrapper
    return old_api(self, *args, **kwargs)
  File
"/usr/lib/python2.7/dist-packages/openerp/addons/auto_backup/backup_scheduler.py",
line 156, in schedule_backup
    logger.notifyChannel('backup', netsvc.LOG_INFO, "Couldn't backup
database %s. Bad database administrator password for server running at
http://%s:%s" %(rec.name, rec.host, rec.port))
Nceback (most recent call last):
  File
"/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_cron.py", line
138, in _callback
    getattr(model, method_name)(cr, uid, *args)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 241, in
wrapper
    return old_api(self, *args, **kwargs)
  File
"/usr/lib/python2.7/dist-packages/openerp/addons/auto_backup/backup_scheduler.py",
line 156, in schedule_backup
    logger.notifyChannel('backup', netsvc.LOG_INFO, "Couldn't backup
database %s. Bad database administrator password for server running at
http://%s:%s" %(rec.name, rec.host, rec.port))
NameError: global name 'logger' is not defined:ameError: global name
'logger' is not defined

**Comment by touctouc** [comment]
Same issue as bridgeway04 

> 2015-10-05 19:46:32,928 13015 INFO None werkzeug: xxx.xxx.xxx.xxx - - [05/Oct/2015 19:46:32] "POST /xmlrpc/db HTTP/1.1" 200 -
2015-10-05 19:46:32,936 13015 ERROR None openerp.http: exp_dump() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 114, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/odoo-server/openerp/service/db.py", line 354, in dispatch
    return g[exp_method_name](*params)
TypeError: exp_dump() takes exactly 2 arguments (1 given)
2015-10-05 19:46:32,938 13015 INFO None werkzeug: xxx.xxx.xxx.xxx - - [05/Oct/2015 19:46:32] "POST /xmlrpc/db HTTP/1.1" 200 -
2015-10-05 19:46:32,940 13015 ERROR boucherie openerp.addons.base.ir.ir_cron: Call of self.pool.get('db.backup').schedule_backup(cr, uid, *()) failed in Job 6
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_cron.py", line 129, in _callback
    getattr(model, method_name)(cr, uid, *args)
  File "/opt/odoo/odoo-server/openerp/api.py", line 223, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/custom/addons/auto_backup/backup_scheduler.py", line 156, in schedule_backup
    _logger.notifyChannel('backup', netsvc.LOG_INFO, "Couldn't backup database %s. Bad database administrator password for server running at http://%s:%s" %(rec.name, rec.host, rec.port))
NameError: global name 'logger' is not defined

I try debugging the code, but I'm to bad in Python yet :/

**Comment by bridgeway04** [comment]
Here is the top half of my openerp-server.conf file, what does yours look like?

[options]
addons_path = /usr/lib/python2.7/dist-packages/openerp/addons
admin_passwd = #@*&+%!@
auto_reload = False
csv_internal_sep = ,
data_dir = /var/lib/odoo/.local/share/Odoo
db_host = False
db_maxconn = 64
db_name = False
db_password = False
db_port = False
db_template = template1
db_user = odoo
dbfilter = .*
debug_mode = False
demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLiteCity.dat
import_partial =
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 60
limit_time_real = 120
list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = error
logfile = /var/log/odoo/odoo-server.log

**Comment by touctouc** [comment]
I made some clean up in the code ... Removing old logger stuff.
The only issue I can't figure out is : 

> 2015-10-05 21:29:15,138 28224 ERROR None openerp.http: exp_dump() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 114, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/odoo-server/openerp/service/db.py", line 354, in dispatch
    return g[exp_method_name](*params)
TypeError: exp_dump() takes exactly 2 arguments (1 given)

Options are reduced to the minimum in v9 : 

> [options]
; This is the password that allows database operations:
db_host = False
db_port = False
db_password = False
db_user = odoo
admin_passwd = xxxx
logfile = /var/log/odoo/odoo-server.log
addons_path=/opt/odoo/odoo-server/addons,/opt/odoo/custom/addons

I added auto_backup with my custom addons folder to keep the odoo src files clean, is this making any difference ? I didn't tested to move the file inside the default addons folder.

**Comment by Yenthe666** [comment]
@bridgeway04 have you managed to change the password? The password is the one from the postgreSQL user running your Odoo db.
@touctouc are you using Odoo V9? It looks like they've changed the function its arguments and added one more in V9. You can see this here: https://github.com/odoo/odoo/blob/9.0/openerp/service/db.py#L140
Looks like you need to pass the format along now too. Judging by this line https://github.com/odoo/odoo/blob/9.0/openerp/service/db.py#L161 I think you should pass along zip.
Could you give this a try and let me know please? I'll have to make a few mods to the 9.0 version.

**Comment by touctouc** [comment]
@Yenthe666 Hey, Thx for the tips about the API changes. I made a fix, and it work well on my server. 

I pushed my changes and ask for a pull request, if you accept. We could in the months add in the backoffice options for the user to choose the backup format. 

Thx for this useful odoo app :+1:

**Comment by Yenthe666** [comment]
@touctouc,

Thanks for the fix! :+1:  It has been merged here: https://github.com/Yenthe666/auto_backup/commit/357154254d9ec1a8c37f3e4c22384c5517fb79f1
The backup options / format is something that I'd like to make but don't have the time for (yet).
