### ISSUE TITLE
[13.0] Problem with ERROR X962

### ISSUE THREAD

**Issue by diezcode** [Yenthe666/auto_backup#190]
Hi, I'm wanted to try the auto_backup sftp backup. I installed pysftp with pip3 install pysftp.
Now when I try to test my connection to my sftp, i get this error:

**Connection Test Failed!

Here is what we got instead:
X962**

In the Odoo Log I get this:

```
2020-09-30 07:16:40,585 1868 ERROR ? paramiko.transport: Unknown exception: X962
2020-09-30 07:16:40,585 1868 ERROR ? paramiko.transport: Traceback (most recent call last):
2020-09-30 07:16:40,585 1868 ERROR ? paramiko.transport:   File "/usr/local/lib/python3.6/dist-packages/paramiko/transport.py", line 2083, in run
2020-09-30 07:16:40,585 1868 ERROR ? paramiko.transport:     self._handler_table[ptype](self, m)
2020-09-30 07:16:40,585 1868 ERROR ? paramiko.transport:   File "/usr/local/lib/python3.6/dist-packages/paramiko/transport.py", line 2199, in _negotiate_keys
2020-09-30 07:16:40,585 1868 ERROR ? paramiko.transport:     self.kex_engine.start_kex()
2020-09-30 07:16:40,586 1868 ERROR ? paramiko.transport:   File "/usr/local/lib/python3.6/dist-packages/paramiko/kex_ecdh_nist.py", line 42, in start_kex
2020-09-30 07:16:40,586 1868 ERROR ? paramiko.transport:     serialization.Encoding.X962,
2020-09-30 07:16:40,586 1868 ERROR ? paramiko.transport:   File "/usr/lib/python3.6/enum.py", line 326, in __getattr__
2020-09-30 07:16:40,586 1868 ERROR ? paramiko.transport:     raise AttributeError(name) from None
2020-09-30 07:16:40,586 1868 ERROR ? paramiko.transport: AttributeError: X962
2020-09-30 07:16:40,586 1868 ERROR ? paramiko.transport:
2020-09-30 07:16:40,586 1868 CRITICAL master odoo.addons.auto_backup.models.db_backup: There was a problem connecting to the remote ftp: X962
2020-09-30 07:16:40,587 1868 WARNING master odoo.http: ('Connection Test Failed!\n\nHere is what we got instead:\nX962', '')


```

Any idea how to solve this problem? thanks a lot.

**Comment by Yenthe666** [comment]
Not really, its an issue with your server though. It could be that your cryptography  and paramiko libraries do not match up (most likely cryptography being very outdated)
