### ISSUE TITLE
[14.0]Problem with install

### ISSUE THREAD

**Issue by lztz0022** [Yenthe666/auto_backup#191]
Hi, Yenthe666, I'm a beginner to Odoo, and I run Odoo 14.0 on windows10. When I install your auto_backup module, I got the following error. But I've already installed paramiko in Python on my system.  How can I install this module correctly?
```
ERROR:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\addons\web\controllers\main.py", line 1363, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\addons\web\controllers\main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\addons\base\models\ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\addons\base\models\ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\addons\base\models\ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\modules\registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\modules\loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\modules\loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\modules\loading.py", line 178, in load_module_graph
    load_openerp_module(package.name)
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\modules\module.py", line 358, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\addons\auto_backup\__init__.py", line 3, in <module>
    from . import models
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\addons\auto_backup\models\__init__.py", line 3, in <module>
    from . import db_backup
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\addons\auto_backup\models\db_backup.py", line 21, in <module>
    'This module needs paramiko to automatically write backups to the FTP through SFTP. '
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 14.0\server\odoo\http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ImportError: This module needs paramiko to automatically write backups to the FTP through SFTP. Please install paramiko on your system. (sudo pip3 install paramiko)
```

**Comment by Yenthe666** [comment]
Hmm, are you sure your Odoo user can access the Python package though?

**Comment by lztz0022** [comment]
> Hmm, are you sure your Odoo user can access the Python package though?

Thank you very much Yenthe666 for your replying. As you pointed out, the Odoo of Windows version comes with a Python environment, and I installed the package in the Python environment of the system. Thank you.
