### ISSUE TITLE
Error Odoo server when installing auto-backup on Odoo community v14 

### ISSUE THREAD

**Issue by marcosmonauta** [Yenthe666/auto_backup#197]
Hi, 
I am working with communigy v14. I installed python3 and paramiko but I get this message when I try to install the app. In the server it is created the direyctory "/usr/local/lib/python3.8/dist-package", but not the one below in the erro message  "/usr/local/lib/python3.7/site-packages/"

I would appreciate help. Thank you all.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 682, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 358, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 911, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 530, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/odoo/addons/web/controllers/main.py", line 1363, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/addons/web/controllers/main.py", line 1351, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_module.py", line 474, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/local/lib/python3.7/site-packages/odoo/addons/base/models/ir_module.py", line 592, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/local/lib/python3.7/site-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/local/lib/python3.7/site-packages/odoo/modules/loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/local/lib/python3.7/site-packages/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/local/lib/python3.7/site-packages/odoo/modules/loading.py", line 178, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/local/lib/python3.7/site-packages/odoo/modules/module.py", line 358, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/mnt/extra-addons/extras/auto_backup/__init__.py", line 3, in <module>
    from . import models
  File "/mnt/extra-addons/extras/auto_backup/models/__init__.py", line 3, in <module>
    from . import db_backup
  File "/mnt/extra-addons/extras/auto_backup/models/db_backup.py", line 21, in <module>
    'This module needs paramiko to automatically write backups to the FTP through SFTP. '
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python3.7/site-packages/odoo/http.py", line 314, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ImportError: This module needs paramiko to automatically write backups to the FTP through SFTP. Please install paramiko on your system. (sudo pip3 install paramiko)

**Comment by Yenthe666** [comment]
How did you install the requirements? Are they available for your Odoo user? Is it the right version?

**Comment by unjoss** [comment]
hello, 

I have exact issue on 13 community ubuntu 18, I did installed odoo using your install script.

xdev@u18dev01:~$ sudo python --version
Python 2.7.17

xdev@u18dev01:~$ sudo pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)


when i run sudo pip3 install paramiko then I got the following output.

The directory '/home/xdev/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.   
The directory '/home/xdev/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.          
Collecting paramiko
  Downloading https://files.pythonhosted.org/packages/95/19/124e9287b43e6ff3ebb9cdea3e5e8e88475a873c05ccdf8b7e20d2c4201e/paramiko-2.7.2-py2.py3-none-any.whl (206kB)
    100% |████████████████████████████████| 215kB 2.0MB/s 
Collecting pynacl>=1.0.1 (from paramiko)
  Downloading https://files.pythonhosted.org/packages/9d/57/2f5e6226a674b2bcb6db531e8b383079b678df5b10cdaa610d6cf20d77ba/PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl (961kB)
    100% |████████████████████████████████| 962kB 1.0MB/s 
Collecting bcrypt>=3.1.3 (from paramiko)
  Downloading https://files.pythonhosted.org/packages/52/a7/51ab6481ac355517696477889d8ab232106a0ddadda642c54e47a2ab40b9/bcrypt-3.2.0-cp36-abi3-manylinux1_x86_64.whl (63kB)
    100% |████████████████████████████████| 71kB 3.4MB/s 
Collecting cryptography>=2.5 (from paramiko)
  Downloading https://files.pythonhosted.org/packages/fa/2d/2154d8cb773064570f48ec0b60258a4522490fcb115a6c7c9423482ca993/cryptography-3.4.6.tar.gz (546kB)
    100% |████████████████████████████████| 552kB 1.8MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-i4wiawlx/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-i4wiawlx/cryptography/

**Comment by unjoss** [comment]
reply to myself this one worked for me:  https://zoomadmin.com/HowToInstall/UbuntuPackage/python3-paramiko

**Comment by dstainhauser** [comment]
Having the same problem as above with Odoo 14 on Ubuntu 20.04, but installing paramiko does not solve the problem.

```
2021-07-28 12:00:13,781 3524 ERROR demo werkzeug: Error on request:
Traceback (most recent call last):
  File "/opt/odoo/14.0/odoo/odoo/modules/registry.py", line 63, in __new__
    return cls.registries[db_name]
  File "/opt/odoo/14.0/odoo/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/odoo/14.0/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'demo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/14.0/all_addons/auto_backup/models/db_backup.py", line 17, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/14.0/env/lib/python3.8/site-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/opt/odoo/14.0/env/lib/python3.8/site-packages/werkzeug/serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/14.0/odoo/odoo/service/wsgi_server.py", line 122, in application
    return ProxyFix(application_unproxied)(environ, start_response)
  File "/opt/odoo/14.0/env/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 232, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/14.0/odoo/odoo/service/wsgi_server.py", line 99, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/odoo/14.0/odoo/odoo/http.py", line 1295, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/14.0/odoo/odoo/http.py", line 1263, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/odoo/14.0/env/lib/python3.8/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/14.0/odoo/odoo/http.py", line 1450, in dispatch
    odoo.registry(db).check_signaling()
  File "/opt/odoo/14.0/odoo/odoo/__init__.py", line 104, in registry
    return modules.registry.Registry(database_name)
  File "/opt/odoo/14.0/odoo/odoo/modules/registry.py", line 65, in __new__
    return cls.new(db_name)
  File "/opt/odoo/14.0/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/14.0/odoo/odoo/modules/loading.py", line 449, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/14.0/odoo/odoo/modules/loading.py", line 346, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/14.0/odoo/odoo/modules/loading.py", line 178, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo/14.0/odoo/odoo/modules/module.py", line 358, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/odoo/14.0/all_addons/auto_backup/__init__.py", line 1, in <module>
    from . import models
  File "/opt/odoo/14.0/all_addons/auto_backup/models/__init__.py", line 2, in <module>
    from . import db_backup
  File "/opt/odoo/14.0/all_addons/auto_backup/models/db_backup.py", line 19, in <module>
    raise ImportError(
ImportError: This module needs paramiko to automatically write backups to the FTP through SFTP. Please install paramiko on your system. (sudo pip3 install paramiko)

```
I also tried to install it through an ubuntu package, without any help.

Any other suggestions?

```
sudo pip3 --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

 sudo pip3 install paramiko
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Requirement already satisfied: paramiko in /usr/local/lib/python3.8/dist-packages (2.7.2)
Requirement already satisfied: cryptography>=2.5 in /usr/local/lib/python3.8/dist-packages (from paramiko) (3.4.7)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python3.8/dist-packages (from paramiko) (3.2.0)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from paramiko) (1.4.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.8/dist-packages (from cryptography>=2.5->paramiko) (1.14.6)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.8/dist-packages (from bcrypt>=3.1.3->paramiko) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.12->cryptography>=2.5->paramiko) (2.20)
```

**Comment by codeagencybe** [comment]
You have to first upgrade python pip with

`pip3 install --upgrade pip`

then run again

`pip3 install paramiko`

Then you can install the app

**Comment by dstainhauser** [comment]
Hi Yenthe

Thanks for your reply. I tried what you suggested, but still having the same problems. Here are the logs, hope you see the cause:

ds@my:~$ sudo pip3 install --upgrade pip
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Collecting pip
  Downloading pip-21.2.4-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 4.1 MB/s 
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-21.2.4
ds@my:~$ pip3 install paramiko
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: paramiko in /usr/local/lib/python3.8/dist-packages (2.7.2)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from paramiko) (1.4.0)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python3.8/dist-packages (from paramiko) (3.2.0)
Requirement already satisfied: cryptography>=2.5 in /usr/local/lib/python3.8/dist-packages (from paramiko) (3.4.7)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.8/dist-packages (from bcrypt>=3.1.3->paramiko) (1.16.0)
Requirement already satisfied: cffi>=1.1 in /usr/local/lib/python3.8/dist-packages (from bcrypt>=3.1.3->paramiko) (1.14.6)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko) (2.20)


Then, when trying to install the Database auto backup App in Odoo

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/14.0/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/14.0/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/14.0/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/14.0/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/14.0/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/14.0/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/14.0/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/14.0/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/14.0/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/14.0/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/14.0/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "/opt/odoo/14.0/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/14.0/odoo/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/14.0/odoo/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/14.0/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/14.0/odoo/odoo/modules/loading.py", line 458, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/14.0/odoo/odoo/modules/loading.py", line 346, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/14.0/odoo/odoo/modules/loading.py", line 178, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo/14.0/odoo/odoo/modules/module.py", line 385, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/odoo/14.0/all_addons/auto_backup/__init__.py", line 1, in <module>
    from . import models
  File "/opt/odoo/14.0/all_addons/auto_backup/models/__init__.py", line 2, in <module>
    from . import db_backup
  File "/opt/odoo/14.0/all_addons/auto_backup/models/db_backup.py", line 19, in <module>
    raise ImportError(
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/14.0/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/14.0/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ImportError: This module needs paramiko to automatically write backups to the FTP through SFTP. Please install paramiko on your system. (sudo pip3 install paramiko)

**Comment by Yenthe666** [comment]
Try a full server restart first 🤔

**Comment by dstainhauser** [comment]
Hi Yenthe

I appreciate your support. 

I restarted the Ubuntu server and then Odoo, but still the same result.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/14.0/env/lib/python3.8/site-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/opt/odoo/14.0/env/lib/python3.8/site-packages/werkzeug/serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/14.0/odoo/odoo/service/wsgi_server.py", line 122, in application
    return ProxyFix(application_unproxied)(environ, start_response)
  File "/opt/odoo/14.0/env/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 232, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/14.0/odoo/odoo/service/wsgi_server.py", line 99, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/odoo/14.0/odoo/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/14.0/odoo/odoo/http.py", line 1272, in __call__
    return self.app(environ, start_wrapped)
  File "/opt/odoo/14.0/env/lib/python3.8/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/14.0/odoo/odoo/http.py", line 1461, in dispatch
    odoo.registry(db).check_signaling()
  File "/opt/odoo/14.0/odoo/odoo/__init__.py", line 104, in registry
    return modules.registry.Registry(database_name)
  File "/opt/odoo/14.0/odoo/odoo/modules/registry.py", line 65, in __new__
    return cls.new(db_name)
  File "/opt/odoo/14.0/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/14.0/odoo/odoo/modules/loading.py", line 454, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/opt/odoo/14.0/odoo/odoo/modules/loading.py", line 346, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/opt/odoo/14.0/odoo/odoo/modules/loading.py", line 178, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo/14.0/odoo/odoo/modules/module.py", line 385, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/odoo/14.0/all_addons/auto_backup_v14/auto_backup/__init__.py", line 1, in <module>
    from . import models
  File "/opt/odoo/14.0/all_addons/auto_backup_v14/auto_backup/models/__init__.py", line 2, in <module>
    from . import db_backup
  File "/opt/odoo/14.0/all_addons/auto_backup_v14/auto_backup/models/db_backup.py", line 19, in <module>
    raise ImportError(
ImportError: This module needs paramiko to automatically write backups to the FTP through SFTP. Please install paramiko on your system. (sudo pip3 install paramiko) - - -

I've also tried to uninstall paramiko with sudo and then installing it again without sudo. Same result

ds@my:/opt/odoo/14.0/all_addons$ pip3 install paramiko
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: paramiko in /usr/local/lib/python3.8/dist-packages (2.7.2)
Requirement already satisfied: cryptography>=2.5 in /usr/local/lib/python3.8/dist-packages (from paramiko) (3.4.7)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from paramiko) (1.4.0)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python3.8/dist-packages (from paramiko) (3.2.0)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.8/dist-packages (from bcrypt>=3.1.3->paramiko) (1.16.0)
Requirement already satisfied: cffi>=1.1 in /usr/local/lib/python3.8/dist-packages (from bcrypt>=3.1.3->paramiko) (1.14.6)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko) (2.20)

ds@my:/opt/odoo/14.0/all_addons$ sudo pip3 uninstall paramiko
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Found existing installation: paramiko 2.7.2
Uninstalling paramiko-2.7.2:
  Would remove:
    /usr/local/lib/python3.8/dist-packages/paramiko-2.7.2.dist-info/*
    /usr/local/lib/python3.8/dist-packages/paramiko/*
Proceed (Y/n)? Y
  Successfully uninstalled paramiko-2.7.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

ds@my:/opt/odoo/14.0/all_addons$ pip3 install paramiko
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: paramiko in /usr/lib/python3/dist-packages (2.6.0)


Then I tried to install paramiko with sudo, same result.

Thanks for any help.

Daniel

**Comment by fengshengxie** [comment]
> Hi Yenthe
> 
> I appreciate your support.
> 
> I restarted the Ubuntu server and then Odoo, but still the same result.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/opt/odoo/14.0/env/lib/python3.8/site-packages/werkzeug/serving.py", line 306, in run_wsgi execute(self.server.app) File "/opt/odoo/14.0/env/lib/python3.8/site-packages/werkzeug/serving.py", line 294, in execute application_iter = app(environ, start_response) File "/opt/odoo/14.0/odoo/odoo/service/wsgi_server.py", line 122, in application return ProxyFix(application_unproxied)(environ, start_response) File "/opt/odoo/14.0/env/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 232, in **call** return self.app(environ, start_response) File "/opt/odoo/14.0/odoo/odoo/service/wsgi_server.py", line 99, in application_unproxied result = odoo.http.root(environ, start_response) File "/opt/odoo/14.0/odoo/odoo/http.py", line 1306, in **call** return self.dispatch(environ, start_response) File "/opt/odoo/14.0/odoo/odoo/http.py", line 1272, in **call** return self.app(environ, start_wrapped) File "/opt/odoo/14.0/env/lib/python3.8/site-packages/werkzeug/middleware/shared_data.py", line 220, in **call** return self.app(environ, start_response) File "/opt/odoo/14.0/odoo/odoo/http.py", line 1461, in dispatch odoo.registry(db).check_signaling() File "/opt/odoo/14.0/odoo/odoo/**init**.py", line 104, in registry return modules.registry.Registry(database_name) File "/opt/odoo/14.0/odoo/odoo/modules/registry.py", line 65, in **new** return cls.new(db_name) File "/opt/odoo/14.0/odoo/odoo/modules/registry.py", line 89, in new odoo.modules.load_modules(registry._db, force_demo, status, update_module) File "/opt/odoo/14.0/odoo/odoo/modules/loading.py", line 454, in load_modules processed_modules += load_marked_modules(cr, graph, File "/opt/odoo/14.0/odoo/odoo/modules/loading.py", line 346, in load_marked_modules loaded, processed = load_module_graph( File "/opt/odoo/14.0/odoo/odoo/modules/loading.py", line 178, in load_module_graph load_openerp_module(package.name) File "/opt/odoo/14.0/odoo/odoo/modules/module.py", line 385, in load_openerp_module **import**('odoo.addons.' + module_name) File "/opt/odoo/14.0/all_addons/auto_backup_v14/auto_backup/**init**.py", line 1, in from . import models File "/opt/odoo/14.0/all_addons/auto_backup_v14/auto_backup/models/**init**.py", line 2, in from . import db_backup File "/opt/odoo/14.0/all_addons/auto_backup_v14/auto_backup/models/db_backup.py", line 19, in raise ImportError( ImportError: This module needs paramiko to automatically write backups to the FTP through SFTP. Please install paramiko on your system. (sudo pip3 install paramiko) - - -
> 
> I've also tried to uninstall paramiko with sudo and then installing it again without sudo. Same result
> 
> ds@my:/opt/odoo/14.0/all_addons$ pip3 install paramiko /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead from cryptography.utils import int_from_bytes /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead from cryptography.utils import int_from_bytes Defaulting to user installation because normal site-packages is not writeable Requirement already satisfied: paramiko in /usr/local/lib/python3.8/dist-packages (2.7.2) Requirement already satisfied: cryptography>=2.5 in /usr/local/lib/python3.8/dist-packages (from paramiko) (3.4.7) Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from paramiko) (1.4.0) Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python3.8/dist-packages (from paramiko) (3.2.0) Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.8/dist-packages (from bcrypt>=3.1.3->paramiko) (1.16.0) Requirement already satisfied: cffi>=1.1 in /usr/local/lib/python3.8/dist-packages (from bcrypt>=3.1.3->paramiko) (1.14.6) Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko) (2.20)
> 
> ds@my:/opt/odoo/14.0/all_addons$ sudo pip3 uninstall paramiko /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead from cryptography.utils import int_from_bytes /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead from cryptography.utils import int_from_bytes Found existing installation: paramiko 2.7.2 Uninstalling paramiko-2.7.2: Would remove: /usr/local/lib/python3.8/dist-packages/paramiko-2.7.2.dist-info/* /usr/local/lib/python3.8/dist-packages/paramiko/* Proceed (Y/n)? Y Successfully uninstalled paramiko-2.7.2 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> 
> ds@my:/opt/odoo/14.0/all_addons$ pip3 install paramiko /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead from cryptography.utils import int_from_bytes /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead from cryptography.utils import int_from_bytes Defaulting to user installation because normal site-packages is not writeable Requirement already satisfied: paramiko in /usr/lib/python3/dist-packages (2.6.0)
> 
> Then I tried to install paramiko with sudo, same result.
> 
> Thanks for any help.
> 
> Daniel

Activate the Virtual environment; (source odoo15-venv/bin/activate)

pip3 install paramiko

**Comment by maarid** [comment]
For me, I had to fix it like this:

1. First of all and a key point is that I had to use _**root**_ user, not ubuntu not odoo nothing, only root
2. I activated my venv in **_root_** user
3. I installed required packages: _pip3 install paramiko_ (or any other packages: _boto3_, or _pretty-bad-protocol_)

and then I could install the module from the odoo admin backend, and it's working just fine

**Comment by phucnb** [comment]
> 

This is the solution. The reason was when we first install odoo, we set up the Python virtual environment for odoo and install Python dependencies in this venv. So we have to go back and install the paramiko in this venv in order to make it works.
