### ISSUE TITLE
ValidateError

### ISSUE THREAD

**Issue by lamnh77** [Yenthe666/auto_backup#20]
Hi Yenthe666,
Thanks for nice module, I was install auto backup, when I configure it's always said:

ValidateError

Field(s) `` failed against a constraint: Error ! No such database exists!

and my log:

2015-10-24 04:54:33,413 21714 ERROR lamnguyen openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 345, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 4092, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 481, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 4283, in _create
    recs._validate_fields(vals)
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 1272, in _validate_fields
    raise ValidationError('\n'.join(errors))
ValidationError: ('ValidateError', u'Field(s) `` failed against a constraint: Error ! No such database exists!')

**Comment by Yenthe666** [comment]
Hi @lamnh77,

Looks like you haven't specified a correct database name to back-up. Could you please make a screenshot of your configuration and place it here? (blur out the password & IP)

**Comment by lamnh77** [comment]
Hi Yenthe666,

I have using local backup, and 3 database, but I have using backup for lamnguyen data. 
There are my screen short:
![configuration](https://cloud.githubusercontent.com/assets/15246684/10725514/2c56e846-7bff-11e5-9e16-4753a0bd9bb4.jpg)
![error](https://cloud.githubusercontent.com/assets/15246684/10725513/2c55d780-7bff-11e5-8819-69580171ffb4.jpg)

**Comment by Yenthe666** [comment]
@lamnh77 are you 100% sure you have a database named "lamnguyen" and that it is not slightly else?
Can you show me a screenshot that shows this database name? I find it strange that the module can't find it.

**Comment by lamnh77** [comment]
Hi yenthe666,

This is screen:
![screenshot_2015-10-26-21-14-53](https://cloud.githubusercontent.com/assets/15246684/10731227/f794bb06-7c26-11e5-9a6c-13eaea60b622.jpg)

**Comment by Yenthe666** [comment]
@lamnh77 I literally have no idea.. I've never seen this before :confused: 
Add log statements to the methods and see where it goes wrong I guess.

**Comment by lamnh77** [comment]
Hi Yenthe666,

This is my log:

2015-10-27 03:20:28,755 11263 INFO lamnguyen werkzeug: 127.0.0.1 - - [27/Oct/2015 03:20:28] "POST /web/dataset/search_read HTTP/1.0" 200 -
2015-10-27 03:20:29,028 11263 INFO lamnguyen werkzeug: 127.0.0.1 - - [27/Oct/2015 03:20:29] "POST /web/dataset/search_read HTTP/1.0" 200 -
2015-10-27 03:20:30,015 11263 INFO lamnguyen openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Gmail
2015-10-27 03:20:32,079 11263 INFO None werkzeug: 127.0.0.1 - - [27/Oct/2015 03:20:32] "POST /xmlrpc/db HTTP/1.1" 200 -
2015-10-27 03:20:32,080 11263 ERROR lamnguyen openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 345, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 4092, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/api.py", line 481, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 4283, in _create
    recs._validate_fields(vals)
  File "/opt/odoo/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo/openerp/models.py", line 1272, in _validate_fields
    raise ValidationError('\n'.join(errors))
ValidationError: ('ValidateError', u'Field(s) `` failed against a constraint: Error ! No such database exists!')
2015-10-27 03:20:32,082 11263 INFO lamnguyen werkzeug: 127.0.0.1 - - [27/Oct/2015 03:20:32] "POST /web/dataset/call_kw/db.backup/create HTTP/1.0" 200 -
2015-10-27 03:20:38,996 11263 INFO lamnguyen werkzeug: 127.0.0.1 - - [27/Oct/2015 03:20:38] "POST /web/dataset/search_read HTTP/1.0" 200 -
2015-10-27 03:20:39,478 11263 INFO lamnguyen werkzeug: 127.0.0.1 - - [27/Oct/2015 03:20:39] "POST /longpolling/poll HTTP/1.0" 200 -
