### ISSUE TITLE
ZIP backup files created are empty

### ISSUE THREAD

**Issue by quique123** [Yenthe666/auto_backup#200]
It seems the files are created but they are empty.  Im using zip type to localhost, Once a Day, priority 5, to a local SSD, number of calls -1, executing python code for db.backup model.  The ZIP files created are empty and when i try to run it manually the file also gets created empty.  When I try to run the backup from the web/database/manager I get a http 500 internal server error.

**Comment by Yenthe666** [comment]
Looks like you have some issue with your Odoo itself. What's in the logs for the "500"? Same log for auto backup & manual backup?

**Comment by quique123** [comment]
Here is the server log right after hitting the run Manually button:

`Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/bus/models/bus.py", line 181, in run
    self.loop()
  File "/opt/odoo/odoo/addons/bus/models/bus.py", line 176, in loop
    event.set()
  File "/opt/odoo/odoo/odoo/sql_db.py", line 404, in __exit__
    self.close()
  File "/opt/odoo/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/sql_db.py", line 288, in close
    return self._close(False)
  File "/opt/odoo/odoo/odoo/sql_db.py", line 318, in _close
    self._cnx.rollback()
psycopg2.InterfaceError: connection already closed
2021-02-02 13:50:38,170 29144 INFO Company_production_2020-12-01_15-17-58 werkzeug: 205.211.254.213 - - [02/Feb/2021 13:50:38] "POST /web/dataset/call_button HTTP/1.1" 500 -
2021-02-02 13:50:38,177 29144 ERROR Company_production_2020-12-01_15-17-58 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/odoo/service/server.py", line 348, in app
    return self.app(e, s)
  File "/opt/odoo/odoo/odoo/service/wsgi_server.py", line 180, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo/odoo/http.py", line 1321, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo/odoo/http.py", line 1295, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo/odoo/http.py", line 1497, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/opt/odoo/odoo/odoo/http.py", line 289, in __exit__
    self._cr.close()
  File "/opt/odoo/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/sql_db.py", line 288, in close
    return self._close(False)
  File "/opt/odoo/odoo/odoo/sql_db.py", line 318, in _close
    self._cnx.rollback()
psycopg2.InterfaceError: connection already closed
2021-02-02 13:50:38,343 29144 INFO Company_production_2020-12-01_15-17-58 odoo.sql_db: Connection to the database failed
2021-02-02 13:50:38,343 29144 INFO Company_production_2020-12-01_15-17-58 odoo.http: Generating nondb routing
2021-02-02 13:50:38,376 29144 INFO Company_production_2020-12-01_15-17-58 werkzeug: 205.211.254.213 - - [02/Feb/2021 13:50:38] "POST /web/dataset/call_kw/ir.cron/read HTTP/1.1" 404 -
2021-02-02 13:50:40,376 29144 INFO Company_production_2020-12-01_15-17-58 werkzeug: 205.211.254.213 - - [02/Feb/2021 13:50:40] "POST /web/webclient/version_info HTTP/1.1" 200 -
2021-02-02 13:50:51,700 29144 INFO Company_production_2020-12-01_15-17-58 werkzeug: 200.52.144.226 - - [02/Feb/2021 13:50:51] "POST /longpolling/poll HTTP/1.1" 200 -`

**Comment by Yenthe666** [comment]
This is where it is coming back from:
```
psycopg2.InterfaceError: connection already closed 2021-02-02 13:50:38,343 29144 INFO Company_production_2020-12-01_15-17-58 odoo.sql_db: Connection to the database failed
```
This is not an issue of our module though but looks like you have a deployment issue. Have you already updated your Odoo to the latest code and made sure that your Odoo/Nginx configs are correct?

**Comment by quique123** [comment]
I am updating it today.  How do I find where that call is coming from?  I thought it was from your module.
