### ISSUE TITLE
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at........)when installed the module.

### ISSUE THREAD

**Issue by lushtech** [Yenthe666/auto_backup#204]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/opt/bitnami/odoo/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/bitnami/odoo/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f905236bbf8>, 'auto_backup.module_management')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 561, in _tag_record
    f_val = self.id_get(f_ref)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 657, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 663, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/bitnami/odoo/odoo/addons/base/models/ir_model.py", line 1685, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "/opt/bitnami/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/bitnami/odoo/odoo/addons/base/models/ir_model.py", line 1674, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: auto_backup.module_management

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/bitnami/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/odoo/odoo/addons/web/controllers/main.py", line 1331, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/odoo/odoo/addons/web/controllers/main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-60>", line 2, in button_immediate_install
  File "/opt/bitnami/odoo/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/bitnami/odoo/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/bitnami/odoo/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/bitnami/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/odoo/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/bitnami/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/bitnami/odoo/odoo/modules/loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/opt/bitnami/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 721, in parse
    exc_info[2]
  File "/opt/bitnami/odoo/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 561, in _tag_record
    f_val = self.id_get(f_ref)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 657, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/opt/bitnami/odoo/odoo/tools/convert.py", line 663, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/opt/bitnami/odoo/odoo/addons/base/models/ir_model.py", line 1685, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "/opt/bitnami/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/bitnami/odoo/odoo/addons/base/models/ir_model.py", line 1674, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: auto_backup.module_management" while parsing /opt/bitnami/odoo/custom-addons/odoo-database-auto-backup/security/user_groups.xml:2, near
<odoo>
  <data>
    <record model="ir.module.category" id="module_management">
      <field name="name">Auto backup access</field>
      <field name="description">User access level for this module</field>
      <field name="sequence">3</field>
    </record>

    <record id="group_manager" model="res.groups">
      <field name="name">Manager</field>
      <field name="category_id" ref="auto_backup.module_management"/>
    </record>
  </data>
</odoo>

anybody knows how to fix it ?

**Comment by lushtech** [comment]
I fixed it by rename the folder of module from odoo-database-auto-backup to auto_backup. Maybe the folder name of the module can not be named with "-", and must be "_"  between the words.
