### ISSUE TITLE
Error with SFTP on auto_backup (Odoo 15 - Windows)

### ISSUE THREAD

**Issue by Barcelonanfactor** [Yenthe666/auto_backup#221]
Hello.

When i test SFTP connection i receive this message.  Could you help me to solve it?

Thanks

```
Traceback (most recent call last):
  File "C:\odoo_company\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\odoo_company\server\odoo\http.py", line 688, in dispatch
    result = self._call_function(**self.params)
  File "C:\odoo_company\server\odoo\http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\odoo_company\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\odoo_company\server\odoo\http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\odoo_company\server\odoo\http.py", line 917, in __call__
    return self.method(*args, **kw)
  File "C:\odoo_company\server\odoo\http.py", line 536, in response_wrap
    response = f(*args, **kw)
  File "C:\odoo_company\server\odoo\addons\web\controllers\main.py", line 1352, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\odoo_company\server\odoo\addons\web\controllers\main.py", line 1340, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\odoo_company\server\odoo\api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\odoo_company\server\odoo\api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\odoo_company\server\odoo\addons\auto_backup\models\db_backup.py", line 112, in test_sftp_connection
    raise Warning(message_title + '\n\n' + message_content + "%s" % str(error))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\odoo_company\server\odoo\http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\odoo_company\server\odoo\http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.exceptions.Warning: Connection Test Failed!

Here is what we got instead:
timed out
```

**Comment by shkmbk** [comment]
I am also getting the same error message while testing smtp connection.
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1351, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1339, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/custom_addon/auto_backup/models/db_backup.py", line 114, in test_sftp_connection
    raise Warning(message_title + '\n\n' + message_content)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.exceptions.Warning: Connection Test Succeeded!
Everything seems properly set up for FTP back-ups!

**Comment by jameelhammadi** [comment]
Me Too 

Plz


  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1330, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1318, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/custom/addons/auto_backup/models/db_backup.py", line 112, in test_sftp_connection
    raise Warning(message_title + '\n\n' + message_content + "%s" % str(error))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.exceptions.Warning: Connection Test Failed!

Here is what we got instead:
timed out

**Comment by Rubas-Mustafa** [comment]
I am also getting this error.

**Comment by nikhilnakrani-tecblic** [comment]
https://www.odoo.com/forum/help-1/connection-test-failed-here-is-what-we-got-instead-timed-out-259870
 
Try check this Please.
