### ISSUE TITLE
Host Settings

### ISSUE THREAD

**Issue by bridgeway04** [Yenthe666/auto_backup#23]
Yenthe666,

I am unable to get the backup to run and the odoo-server.log log says it's a bad db admin password. After troubleshooting different passwords in the openerp-server.conf file, I think it's failing because of bad configuration settings in the module.  

My server redirects from the default http://localhost:8069  to https://mangstor.com/ but when I enter mangstor or mangstor.com as the host I get a Validation Error: Field(s) `` failed against a constraint: Error ! No such database exists!  I have also tried changing the port number to 443 but no luck.

What do I enter as my host?

Brad

**Comment by Yenthe666** [comment]
Hi @bridgeway04,

You can see an example here: <img src="https://www.odoo.com/apps/modules/9.0/auto_backup/overview.png" alt="Example settings"/>

**Comment by bridgeway04** [comment]
I have tried the defaults!

In your tutorial you say:

*Host*: This is the name that you use on your local server to open up Odoo.
For example if you have a local Ubuntu VM with an Odoo that you can access
from http://localhost:8069/ you should fill in localhost (which is correct
in 99% of the cases)!

*If you have http://anothername:8069/ <http://anothername:8069/> you should
fill in anothername.*


*My website redirects to domain.com <http://domain.com> without any port
numbers! What do I do in this case?*

*Brad*

**Comment by sergueikp** [comment]
Hello Yenthe666, 
I'm trying to configure auto_backup but I get the error message:
ValidateError
Field(s) `` failed against a constraint: Error ! No such database exists!

My OS is Ubuntu 14.04 on the OVH VPS, Odoo 8.0 nightly build 12/04/2017
**I've configured apache to redirect to https;**
Here are my configurations:
Host: localhost
Database: aramis_test1
Port: 443
Backup Directory: /odoo/backups

I've tried it with different ports: like 80 or 8080 or 8069; 

**This is server log:**
2017-04-15 10:37:51,499 1914 ERROR aramis_test1 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/models.py", line 4104, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/models.py", line 4301, in _create
    recs._validate_fields(vals)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/models.py", line 1275, in _validate_fields
    raise ValidationError('\n'.join(errors))
ValidationError: ('ValidateError', u'Field(s) `` failed against a constraint: Error ! No such database exists!')
2017-04-15 10:37:56,264 1914 ERROR aramis_test1 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/models.py", line 4104, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/models.py", line 4301, in _create
    recs._validate_fields(vals)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo-8.0-17/apps/odoo/lib/odoo-8.0.post20170412-py2.7.egg/openerp/models.py", line 1275, in _validate_fields
    raise ValidationError('\n'.join(errors))
ValidationError: ('ValidateError', u'Field(s) `` failed against a constraint: Error ! No such database exists!')

Can you please help me?

**Comment by sergueikp** [comment]
Hi, I found the reason if this error:
ValidateError
Field(s) `` failed against a constraint: Error ! No such database exists!

It is because I force to connect through https, I'm adding this code to the file apache2/conf/bitnami/bitnami.conf":
<VirtualHost _default_:80>
  DocumentRoot "/home/ubuntu/odoo-8.0-5/apache2/htdocs"
  RewriteEngine On
  RewriteCond %{HTTPS} !=on
  RewriteRule ^/(.*) https://%{SERVER_NAME}/$1 [R,L]

But now my question is how to configure auto_backup when https connection is enabled?
