### ISSUE TITLE
Can't establish connection with external SFTP server 

### ISSUE THREAD

**Issue by mamunzihad** [Yenthe666/auto_backup#231]
@Yenthe666 
2022-08-23 07:27:10,428 24872 INFO Yuko_Apps_Live odoo.addons.auto_backup.models.db_backup: Connection Test Failed!
Traceback (most recent call last):
  File "/odoo/custom/yuko-git/server-tools/auto_backup/models/db_backup.py", line 127, in action_sftp_test_connection
    with self.sftp_connection():
  File "/odoo/custom/yuko-git/server-tools/auto_backup/models/db_backup.py", line 294, in sftp_connection
    return pysftp.Connection(**params)
  File "/usr/local/lib/python2.7/dist-packages/pysftp/__init__.py", line 132, in __init__
    self._tconnect['hostkey'] = self._cnopts.get_hostkey(host)
  File "/usr/local/lib/python2.7/dist-packages/pysftp/__init__.py", line 71, in get_hostkey
    raise SSHException("No hostkey for host %s found." % host)
SSHException: No hostkey for host cloud.yukoleather.com.bd found.

I have tested connection using filezilla, it is working from ip & URL also, it is successful.

**Comment by mamunzihad** [comment]
Issue Resolved.
Actually the issue was about user name of two servers. Both servers user name shouldn't be same.

**Comment by Yenthe666** [comment]
Thanks for answering your own issue :)
