### ISSUE TITLE
Odoo backup

### ISSUE THREAD

**Issue by naesellor** [Yenthe666/auto_backup#32]
I backed up the folder odoo and copied to a new machine running odoo and replaced the folder.  I believe my issue is user odoo does not have rights

**Comment by Yenthe666** [comment]
@naesellor if this is the change then change the rights of the folders / user.
If this does not fix it I'll need more details.

**Comment by aliaamokhtar** [comment]
i have the same issue while run scheduler 
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/odoo-11.0/odoo/tools/safe_eval.py", line 348, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/odoo-11.0/addons/auto_backup/models/db_backup.py", line 152, in schedule_backup
    os.makedirs(rec.folder)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/odoo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/odoo-11.0/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-11.0/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/odoo-11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/odoo-11.0/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo-11.0/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-11.0/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/odoo-11.0/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo-11.0/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-11.0/addons/web/controllers/main.py", line 924, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo-11.0/addons/web/controllers/main.py", line 912, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/odoo-11.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/odoo-11.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo-11.0/odoo/addons/base/ir/ir_cron.py", line 67, in method_direct_trigger
    self.sudo(user=cron.user_id.id).ir_actions_server_id.run()
  File "/home/odoo/odoo-11.0/odoo/addons/base/ir/ir_actions.py", line 536, in run
    res = func(action, eval_context=eval_context)
  File "/home/odoo/odoo-11.0/addons/website/models/ir_actions.py", line 57, in run_action_code_multi
    res = super(ServerAction, self).run_action_code_multi(action, eval_context)
  File "/home/odoo/odoo-11.0/odoo/addons/base/ir/ir_actions.py", line 417, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/home/odoo/odoo-11.0/odoo/tools/safe_eval.py", line 371, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/home/odoo/odoo-11.0/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/odoo/odoo-11.0/odoo/tools/safe_eval.py", line 348, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/odoo-11.0/addons/auto_backup/models/db_backup.py", line 152, in schedule_backup
    os.makedirs(rec.folder)
  File "/usr/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
ValueError: <class 'PermissionError'>: "13
Permission denied" while evaluating
'model.schedule_backup()'

while i give user manger access to db_backup module
