### ISSUE TITLE
[8.0] Error No such database exists

### ISSUE THREAD

**Issue by mamaf** [Yenthe666/auto_backup#56]
I got this error, but the database exists (I'm connected on it)
![error auto_backup](https://cloud.githubusercontent.com/assets/956701/22249868/10466eee-e245-11e6-8058-1a49999800d8.png)

**Comment by diezcode** [comment]
You forgot to put the right port of odoo in the "Port" field.
Standard Odoo installation is on Port: 8069

**Comment by mamaf** [comment]
We don't use the standard port
So we specified it in the configuration

details of the error in the log :
2017-01-24 13:49:13,160 30175 ERROR o80_destock-dev openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/destock/6it_dev/odoo/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/destock/6it_dev/odoo/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/destock/6it_dev/odoo/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/destock/6it_dev/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/destock/6it_dev/odoo/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/destock/6it_dev/odoo/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/destock/6it_dev/odoo/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/destock/6it_dev/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/destock/6it_dev/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/destock/6it_dev/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/destock/6it_dev/odoo/openerp/api.py", line 372, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/destock/6it_dev/odoo/openerp/models.py", line 4104, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/destock/6it_dev/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/destock/6it_dev/odoo/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/destock/6it_dev/odoo/openerp/models.py", line 4301, in _create
    recs._validate_fields(vals)
  File "/opt/odoo/destock/6it_dev/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/destock/6it_dev/odoo/openerp/models.py", line 1275, in _validate_fields
    raise ValidationError('\n'.join(errors))
ValidationError: ('ValidateError', u"Champ(s)  `` en erreur vis \xe0 vis de la contrainte : Error ! No such database exists!\n\nD\xe9tails de l'erreur :\n''  ")

**Comment by diezcode** [comment]
What port are you using on odoo? Try to put the odoo port in there. 5432 is the postgres port
An other problem that I know is that the backup directory on the server needs to have the odoo user rights.
sudo chown -R odoo:odoo /opt/odoo/backups

**Comment by Yenthe666** [comment]
Indeed port 5432 is reserved by postgreSQL and Odoo should run on another. Can you double check this?

**Comment by mamaf** [comment]
OK
It was a problem of port number ;-)
Sorry
