### ISSUE TITLE
Error installing on Odoo v10.

### ISSUE THREAD

**Issue by thiago95macedo** [Yenthe666/auto_backup#62]
Error installing on Odoo v10.
The following error message is displayed:

Traceback (most recent call last):
  File "/opt/adax/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/adax/odoo/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/opt/adax/odoo/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/adax/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/adax/odoo/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/adax/odoo/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/opt/adax/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/adax/odoo/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/adax/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/adax/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/adax/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/adax/odoo/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/adax/odoo/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/adax/odoo/odoo/modules/registry.py", line 82, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/adax/odoo/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/opt/adax/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/adax/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/adax/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/adax/odoo/odoo/tools/convert.py", line 845, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/adax/odoo/odoo/tools/convert.py", line 915, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/adax/odoo/odoo/tools/convert.py", line 796, in parse
    self.parse(rec, mode)
  File "/opt/adax/odoo/odoo/tools/convert.py", line 799, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/adax/odoo/odoo/tools/convert.py", line 707, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/adax/odoo/odoo/addons/base/ir/ir_model.py", line 1228, in _update
    record = record.create(values)
  File "/opt/adax/odoo/odoo/addons/base/ir/ir_ui_view.py", line 362, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/adax/odoo/odoo/models.py", line 3838, in create
    self._fields[key].determine_inverse(record)
  File "/opt/adax/odoo/odoo/fields.py", line 1000, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/adax/odoo/odoo/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "/opt/adax/odoo/odoo/addons/base/ir/ir_ui_view.py", line 380, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/adax/odoo/odoo/models.py", line 3564, in write
    self._write(old_vals)
  File "/opt/adax/odoo/odoo/models.py", line 3715, in _write
    self._validate_fields(vals)
  File "/opt/adax/odoo/odoo/models.py", line 1083, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "Error while validating constraint

Modelo n\xe3o encontrado: db.backup

Contexto de erro:
Veja `Configure Backup`
[view_id: 1063, xml_id: n/a, model: db.backup, parent_id: n/a]
None" while parsing /opt/adax/odoo-brasil/auto_backup/bkp_conf_view.xml:4, near
<record model="ir.ui.view" id="view_backup_conf_form">
			<field name="name">Configure Backup</field>
			<field name="model">db.backup</field>
			<field name="type">form</field>
			<field name="arch" type="xml">
				<form string="Test">
					<group col="4" colspan="4">
						<separator col="2" string="Local backup configuration"/>
                    			</group>
					<group>
						<field name="host" colspan="2"/>
						<field name="name"/>
						<field name="port"/>
						<field name="bkp_dir"/>
						<field name="autoremove"/>
						<field name="daystokeep" attrs="{'invisible': [('autoremove','=',False)]}"/>

					</group>
					<group col="4" colspan="4">
						<separator col="2" string="SFTP"/>
                    			</group>
<div style="width:50%;border-radius:10px;margin: 10px 0px;padding:15px 10px 15px 10px; background-repeat: no-repeat;background-position: 10px center;color: #9F6000;background-color: #FEEFB3;" attrs="{'invisible': [('sftpwrite','=',False)]}"><b>Warning:</b> Use SFTP with caution! This writes files to external servers under the path you specify.</div>
					<group>
						<field name="sftpwrite"/>
						<field name="sftpip" attrs="{'invisible':[('sftpwrite', '==', False)],'required':[('sftpwrite', '==', True)]}"/>
						<field name="sftpusername" attrs="{'invisible':[('sftpwrite', '==', False)],'required':[('sftpwrite', '==', True)]}"/>
						<field name="sftppassword" attrs="{'invisible':[('sftpwrite', '==', False)],'required':[('sftpwrite', '==', True)]}" password="True"/>
						<field name="sftppath" attrs="{'invisible':[('sftpwrite', '==', False)],'required':[('sftpwrite', '==', True)]}" placeholder="For example: /odoo/backups/"/>
						<field name="daystokeepsftp" attrs="{'invisible':[('sftpwrite', '==', False)],'required':[('sftpwrite', '==', True)]}"/>
						<field name="sendmailsftpfail" attrs="{'invisible': [('sftpwrite','=',False)]}"/>
						<field name="emailtonotify" attrs="{'invisible':['|',('sendmailsftpfail', '==', False),       ('sftpwrite', '==', False)],'required':[('sendmailsftpfail', '==', True)]}"/>
						<button name="test_sftp_connection" type="object" attrs="{'invisible': [('sftpwrite','=',False)]}" string="Test SFTP Connection" icon="gtk-network"/>
					</group>
                    			<separator string="Help" colspan="2"/>
                    			<div>
						This configures the scheduler for automatic backup of the given database running on given host at given port on regular intervals.
						<br/>
						Automatic backups of the database can be scheduled as follows: 
						<ol>
							<li>
								Go to Settings / Technical / Automation / Scheduled Actions.
							</li>
							<li>
								Search the action named 'Backup scheduler'.
							</li>
							<li>
								Set the scheduler to active and fill in how often you want backups generated.
							</li>
						</ol>
						<p style="font-size:18px;">
						Need more help? <a href="mailto:yenthe.vanginneken@vanroey.be">Contact us!</a>
						</p>
					</div>
				</form>
			</field>
	</record>

**Comment by thsdrouot** [comment]
Hi,

Did you deploy with Docker ? I get this error too.
Impossible to install sftp with pip install inside the container.

**Comment by Yenthe666** [comment]
Hi @thsdrouot,

Thank you for the response! Did you try this on docker and is that where this error is coming from?

**Comment by thsdrouot** [comment]
Hi @Yenthe666,

I tried to install the addons on the module page after loaded it : I got an error. 
So, I supposed the official Odoo image had no ftp feature as needed. I tried directly to install this feature with "pip install pyftp" inside the running container but I got also an error.

I did that very fast. It worth to do more to know why it is not working.

**Comment by Yenthe666** [comment]
Hi @thsdrouot,

Thanks for the extra feedback. The issue is that I had multiple people report this issue but I've never reproduced it nor do I have an idea where it comes from.
@thiago95macedo are you on Docker too?

**Comment by thiago95macedo** [comment]
No ... I did my installation manually.
I have a problem with my server, and I am trying to install apt-get update.

Now I'm having trouble using the bkp function with sftp, always the error in the connection test.

**Comment by Yenthe666** [comment]
This might actually be related to https://github.com/Yenthe666/auto_backup/issues/65 too. Could one of you check?
