### ISSUE TITLE
after install pysftp on a Ubuntu 16.04.3 LTS odoo not starting.

### ISSUE THREAD

**Issue by giordano-ch** [Yenthe666/auto_backup#71]
I have a problem with auto_backup and odoo.
First I installed a new Odoo10 Enterprise on the Ubuntu Server with @Yenthe666 installation script.
Then I installed pysftp:
sudo pip install pysftp
- installation was successful

After I tried to restart the Odoo10 server nothing happends, Odoo can't start again. 
Then I wanted to uninstall pysftp with this:
sudo pip uninstall pysftp. - and I get this error:

**test@test:/odoo10$ sudo pip uninstall pysftp
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 13, in <module>
    from pip.exceptions import InstallationError, CommandError, PipError
  File "/usr/lib/python2.7/dist-packages/pip/exceptions.py", line 6, in <module>
    from pip._vendor.six import iteritems
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 64, in <module>
    vendored("cachecontrol")
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
  File "/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/adapter.py", line 3, in <module>
  File "/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/__init__.py", line 53, in <module>
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 54, in <module>
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'**

any help on this?

**Comment by MichelWorld** [comment]
Hi,

the solution on this page worked for me: 

https://stackoverflow.com/questions/41102299/unable-to-install-any-pip-module-module-object-has-no-attribute-cryptography

**Comment by Yenthe666** [comment]
Thanks @MichelWorld 😉

**Comment by jbendezug** [comment]
Gracias MichelWorld
