### ISSUE TITLE
 Error reading SSH protocol banner[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by manaka02** [Yenthe666/auto_backup#81]
Hello guys,
First, thank you very much for this,
I installed **pysftp** with **pip3** already installed with odoo 11 and when I try to connect by SFTP, I always have this error 
 
```
2017-12-28 05:51:56,140 1 ERROR ? paramiko.transport: Exception: Error reading SSH protocol banner[Errno 104] Connection reset by peer
2017-12-28 05:51:56,146 1 ERROR ? paramiko.transport: Traceback (most recent call last):
2017-12-28 05:51:56,147 1 ERROR ? paramiko.transport:   File "/var/lib/odoo/.local/lib/python3.5/site-packages/paramiko/transport.py", line 2003, in _check_banner
2017-12-28 05:51:56,147 1 ERROR ? paramiko.transport:     buf = self.packetizer.readline(timeout)
2017-12-28 05:51:56,148 1 ERROR ? paramiko.transport:   File "/var/lib/odoo/.local/lib/python3.5/site-packages/paramiko/packet.py", line 353, in readline
2017-12-28 05:51:56,148 1 ERROR ? paramiko.transport:     buf += self._read_timeout(timeout)
2017-12-28 05:51:56,149 1 ERROR ? paramiko.transport:   File "/var/lib/odoo/.local/lib/python3.5/site-packages/paramiko/packet.py", line 540, in _read_timeout
2017-12-28 05:51:56,149 1 ERROR ? paramiko.transport:     x = self.__socket.recv(128)
2017-12-28 05:51:56,150 1 ERROR ? paramiko.transport: ConnectionResetError: [Errno 104] Connection reset by peer
2017-12-28 05:51:56,151 1 ERROR ? paramiko.transport: 
2017-12-28 05:51:56,151 1 ERROR ? paramiko.transport: During handling of the above exception, another exception occurred:
2017-12-28 05:51:56,152 1 ERROR ? paramiko.transport: 
2017-12-28 05:51:56,152 1 ERROR ? paramiko.transport: Traceback (most recent call last):
2017-12-28 05:51:56,153 1 ERROR ? paramiko.transport:   File "/var/lib/odoo/.local/lib/python3.5/site-packages/paramiko/transport.py", line 1856, in run
2017-12-28 05:51:56,153 1 ERROR ? paramiko.transport:     self._check_banner()
2017-12-28 05:51:56,154 1 ERROR ? paramiko.transport:   File "/var/lib/odoo/.local/lib/python3.5/site-packages/paramiko/transport.py", line 2008, in _check_banner
2017-12-28 05:51:56,155 1 ERROR ? paramiko.transport:     'Error reading SSH protocol banner' + str(e)
2017-12-28 05:51:56,155 1 ERROR ? paramiko.transport: paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
2017-12-28 05:51:56,156 1 ERROR ? paramiko.transport: 
2017-12-28 05:51:56,156 1 CRITICAL odoo11 odoo.addons.auto_backup.models.db_backup: There was a problem connecting to the remote ftp: Error reading SSH protocol banner[Errno 104] Connection reset by peer
2017-12-28 05:51:56,166 1 INFO odoo11 werkzeug: 172.18.0.3 - - [28/Dec/2017 05:51:56] "POST /web/dataset/call_button HTTP/1.1" 200 -
2017-12-28 05:51:56,258 1 ERROR ? paramiko.transport: Exception: Error reading SSH protocol banner[Errno 104] Connection reset by peer
2017-12-28 05:51:56,261 1 ERROR ? paramiko.transport: Traceback (most recent call last):
2017-12-28 05:51:56,262 1 ERROR ? paramiko.transport:   File "/var/lib/odoo/.local/lib/python3.5/site-packages/paramiko/transport.py", line 2003, in _check_banner
2017-12-28 05:51:56,263 1 ERROR ? paramiko.transport:     buf = self.packetizer.readline(timeout)
2017-12-28 05:51:56,263 1 ERROR ? paramiko.transport:   File "/var/lib/odoo/.local/lib/python3.5/site-packages/paramiko/packet.py", line 353, in readline
2017-12-28 05:51:56,264 1 ERROR ? paramiko.transport:     buf += self._read_timeout(timeout)
2017-12-28 05:51:56,264 1 ERROR ? paramiko.transport:   File "/var/lib/odoo/.local/lib/python3.5/site-packages/paramiko/packet.py", line 540, in _read_timeout
2017-12-28 05:51:56,265 1 ERROR ? paramiko.transport:     x = self.__socket.recv(128)
2017-12-28 05:51:56,265 1 ERROR ? paramiko.transport: ConnectionResetError: [Errno 104] Connection reset by peer
2017-12-28 05:51:56,266 1 ERROR ? paramiko.transport: 
2017-12-28 05:51:56,266 1 ERROR ? paramiko.transport: During handling of the above exception, another exception occurred:
2017-12-28 05:51:56,267 1 ERROR ? paramiko.transport: 
2017-12-28 05:51:56,268 1 ERROR ? paramiko.transport: Traceback (most recent call last):
2017-12-28 05:51:56,268 1 ERROR ? paramiko.transport:   File "/var/lib/odoo/.local/lib/python3.5/site-packages/paramiko/transport.py", line 1856, in run
2017-12-28 05:51:56,269 1 ERROR ? paramiko.transport:     self._check_banner()
2017-12-28 05:51:56,270 1 ERROR ? paramiko.transport:   File "/var/lib/odoo/.local/lib/python3.5/site-packages/paramiko/transport.py", line 2008, in _check_banner
2017-12-28 05:51:56,270 1 ERROR ? paramiko.transport:     'Error reading SSH protocol banner' + str(e)
2017-12-28 05:51:56,271 1 ERROR ? paramiko.transport: paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
2017-12-28 05:51:56,271 1 ERROR ? paramiko.transport:
```

I don't know what happened, if you can help me XD

**Comment by Yenthe666** [comment]
Hi @manaka02,

Could you please remove paramiko, install it again and reboot your server as a first try?

Regards,
Yenthe

**Comment by manaka02** [comment]
Hi @Yenthe666, It's my fault so sorry, I used FTP client instead of SFTP client. 
Thanks for your help
