### ISSUE TITLE
Help - error install

### ISSUE THREAD

**Issue by ghost** [Yenthe666/auto_backup#82]
Erro:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/adax-erp/travelturismo/core/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/adax-erp/travelturismo/core/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/adax-erp/travelturismo/core/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/opt/adax-erp/travelturismo/core/odoo/addons/base/ir/ir_cron.py", line 70, in create
    return super(ir_cron, self).create(values)
  File "/opt/adax-erp/travelturismo/core/odoo/models.py", line 3278, in create
    record = self.browse(self._create(old_vals))
  File "/opt/adax-erp/travelturismo/core/odoo/models.py", line 3335, in _create
    parent_id = self.env[parent_model].create(parent_vals).id
  File "/opt/adax-erp/travelturismo/core/odoo/addons/base/ir/ir_actions.py", line 46, in create
    res = super(IrActions, self).create(vals)
  File "/opt/adax-erp/travelturismo/core/odoo/models.py", line 3278, in create
    record = self.browse(self._create(old_vals))
  File "/opt/adax-erp/travelturismo/core/odoo/models.py", line 3371, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/opt/adax-erp/travelturismo/core/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/adax-erp/travelturismo/core/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (486, Backup scheduler, ir.actions.server, null, null, action, 1, 2017-12-28 18:48:53.082475, 1, 2017-12-28 18:48:53.082475, ir_cron, object_write, 5, null, null, # Available variables:
#  - env: Odoo Environment on which the a..., null, null, null).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/adax-erp/travelturismo/core/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/adax-erp/travelturismo/core/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/adax-erp/travelturismo/core/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/adax-erp/travelturismo/core/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/adax-erp/travelturismo/core/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/adax-erp/travelturismo/core/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/adax-erp/travelturismo/core/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/adax-erp/travelturismo/core/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/adax-erp/travelturismo/core/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/adax-erp/travelturismo/core/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/adax-erp/travelturismo/core/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/adax-erp/travelturismo/core/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/adax-erp/travelturismo/core/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "/opt/adax-erp/travelturismo/core/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/adax-erp/travelturismo/core/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/adax-erp/travelturismo/core/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/adax-erp/travelturismo/core/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/adax-erp/travelturismo/core/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/opt/adax-erp/travelturismo/core/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/adax-erp/travelturismo/core/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/adax-erp/travelturismo/core/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/adax-erp/travelturismo/core/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/adax-erp/travelturismo/core/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/adax-erp/travelturismo/core/odoo/tools/convert.py", line 738, in parse
    self.parse(rec, mode)
  File "/opt/adax-erp/travelturismo/core/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/opt/adax-erp/travelturismo/core/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/adax-erp/travelturismo/core/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/adax-erp/travelturismo/core/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/adax-erp/travelturismo/core/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/opt/adax-erp/travelturismo/core/odoo/addons/base/ir/ir_cron.py", line 70, in create
    return super(ir_cron, self).create(values)
  File "/opt/adax-erp/travelturismo/core/odoo/models.py", line 3278, in create
    record = self.browse(self._create(old_vals))
  File "/opt/adax-erp/travelturismo/core/odoo/models.py", line 3335, in _create
    parent_id = self.env[parent_model].create(parent_vals).id
  File "/opt/adax-erp/travelturismo/core/odoo/addons/base/ir/ir_actions.py", line 46, in create
    res = super(IrActions, self).create(vals)
  File "/opt/adax-erp/travelturismo/core/odoo/models.py", line 3278, in create
    record = self.browse(self._create(old_vals))
  File "/opt/adax-erp/travelturismo/core/odoo/models.py", line 3371, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/opt/adax-erp/travelturismo/core/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/adax-erp/travelturismo/core/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "null value in column "model_id" violates not-null constraint
DETAIL:  Failing row contains (486, Backup scheduler, ir.actions.server, null, null, action, 1, 2017-12-28 18:48:53.082475, 1, 2017-12-28 18:48:53.082475, ir_cron, object_write, 5, null, null, # Available variables:
#  - env: Odoo Environment on which the a..., null, null, null).
" while parsing /opt/adax-erp/travelturismo/modulos/backend/auto_backup/data/backup_data.xml:4, near
<record id="backup_scheduler" model="ir.cron">
      <field name="function">schedule_backup</field>
      <field name="interval_type">work_days</field>
      <field name="name">Backup scheduler</field>
      <field name="numbercall">-1</field>
      <field name="priority">5</field>
      <field name="doall">False</field>
      <field name="active">False</field>
      <field name="interval_number">1</field>
      <field name="model">db.backup</field>
    </record>

**Comment by Yenthe666** [comment]
Hi @thiago95macedo,

Which version of Odoo are you using? Did you take the latest source code?

**Comment by ghost** [comment]
Hi @Yenthe666 

Version 11.
Yes, I'm using the latest version.

**Comment by Yenthe666** [comment]
hmm odd.. Have you tried a `-u auto_backup`?

**Comment by ghost** [comment]
Friend, that's settled, it was my carelessness, lack of attention.

Thank you very much for your attention.

**Comment by Yenthe666** [comment]
Awesome, thanks for the feedback!
