### ISSUE TITLE
I can't install module on Windows 7 server.

### ISSUE THREAD

**Issue by bouet** [Yenthe666/auto_backup#86]
I need your help because i’m actually trying to install your module call « Auto Backup » to my Odoo 11.

I’ve installed Odoo on a Windows 7 computer and followed the step on your website : http://www.odoo.yenthevg.com/automated-backups-in-odoo/

So after downloaded the module for Odoo 11, i've unzip and copy it to: C:\Program Files (x86)\Odoo 11.0\server\addons

Then i've installed Python 2.7.14 and tried to execute in cmd.exe: pip install pysftp

It tell me that "Pip n'est pas reconnu comme une commande interne ou externe' or in english "Pip is not recognized as an internal or external command.
So i've unistalled Python 2.7 to install Python 3.6.4 but same error.

So i've searched again on Google and find a command: pip install Django==1.8.5
After that i was able to do: pip install pysftp

But when i get back to Odoo and update the applications list nothing appear.

I've tried to restart the server but nothing more appear.

Can you help me ?

**Comment by Yenthe666** [comment]
Hi @bouet,

Have a look at https://www.odoo.com/nl_NL/forum/help-1/question/how-to-install-pysftp-to-backup-data-87180 please - this should answer your questions!

Regards,
Yenthe

**Comment by bouet** [comment]
Thanks, problem was not coming from module but from Python installation.
Now there is an other problem, i'm trying to find: 'Configure Backup’ under Settings > Configuration.
I've put the folder "auto_backup" in "C:\Program Files (x86)\Odoo 11.0\server\addons" and installed it.
But then there is nothing in "Settings" --> "General Settings" --> "Configure Backup". (Refer to screenshot)
![screen_backup](https://user-images.githubusercontent.com/25053359/35615629-015f8b4c-0673-11e8-8149-8f8f91c95d31.png)


But before it was in "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons" and was getting this error:
`Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\auto_backup\models\db_backup.py", line 24, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\web\controllers\main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-39>", line 2, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\module\module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\module\module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\base\module\module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\loading.py", line 121, in load_module_graph
    load_openerp_module(package.name)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\module.py", line 368, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\modules\module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 3, in <module>
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\auto_backup\models\__init__.py", line 3, in <module>
    from . import db_backup
  File "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons\auto_backup\models\db_backup.py", line 27, in <module>
    'This module needs paramiko to automatically write backups to the FTP through SFTP. Please install paramiko on your system. (sudo pip3 install paramiko)')
ImportError: This module needs paramiko to automatically write backups to the FTP through SFTP. Please install paramiko on your system. (sudo pip3 install paramiko)`

**Comment by Yenthe666** [comment]
@bouet can you activate developer mode? You should absolutely see it with the administrator account then.

**Comment by bouet** [comment]
@Yenthe666 developer mode is already active ..
I think the problem is comming from the installation because when i click on "Install" then it display the home page and i need to re-activate the developer mode.
But when i got to the module it tell me the state: "To install".
![autobackup_prob](https://user-images.githubusercontent.com/25053359/35616578-f9021ee4-0675-11e8-8d11-6df3421b9dec.png)
If we compare to a module that is installed:
![module_prob](https://user-images.githubusercontent.com/25053359/35616588-028e8394-0676-11e8-8546-2c91a111c17d.png)
Sorry for the french language on these screenshots, if need translation you can ask me.

**Comment by Yenthe666** [comment]
Yep - it didn't fully succeed. Try to deinstall it and reinstall it again. Usually that fixes the issue.

**Comment by bouet** [comment]
Ok so here are the steps i've followed:
1) Cancel module's installation
2) Restart the server with "Windows Services"
3) Configuration --> Activate "Developer Mode"
4) Applications --> Update Applications List
5) Search Toolbar --> "Auto" 
6) "Database auto-backup" --> Install
7) Make me back to home page
8) Restart the server
9) Configuration --> Activate Developer Mode

Still nothing appear, does the "Developer mode with assets" change something ?
I don't understand from where problem is coming and the module still in "to install" state.

**Comment by Yenthe666** [comment]
@bouet the "Developer mode with assets" is to compile all assets; which is easier to debug JavaScript and CSS related issue mainly.
As for the module installation: I've only developed & used it for Linux. I know some people are running it on Windows but they all had to use another approach to get it working (depending on the OS etcetera).
I guess you should have a look at your logfiles and try to update the module from the command line.

P.S: Always try to install & run Odoo from Linux when you can.

**Comment by bouet** [comment]
@Yenthe666 I'm actually a trainee for a company and they don't want to install on Linux.
I am beginner with Odoo and his language so i don't know where are the log files and how to input command line .
But thanks for your help i'll continue to search !

**Comment by Yenthe666** [comment]
@bouet you should probably convince them to switch to Linux though. Better uptimes, almost everybody that uses Odoo uses Linux so you get way more info/feedback.
The logfile is under `/var/log` in Linux but I believe there is a `log` or `logs` folder on Windows too for this.

**Comment by bouet** [comment]
2018-01-31 13:49:50,579 1680 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:49:50] "POST /web/dataset/call_kw/ir.module.module/read HTTP/1.1" 200 -
2018-01-31 13:49:50,606 1680 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:49:50] "POST /web/dataset/call_kw/ir.module.module.dependency/read HTTP/1.1" 200 -
2018-01-31 13:49:50,643 1680 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:49:50] "POST /web/dataset/call_kw/ir.module.category/name_search HTTP/1.1" 200 -
2018-01-31 13:49:50,724 1680 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:49:50] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-01-31 13:49:50,729 1680 INFO ? werkzeug: 192.168.1.64 - - [31/Jan/2018 13:49:50] "GET /base/static/src/css/description.css HTTP/1.1" 200 -
2018-01-31 13:49:50,731 1680 INFO ? werkzeug: 192.168.1.64 - - [31/Jan/2018 13:49:50] "GET /web/static/src/img/placeholder.png HTTP/1.1" 200 -
2018-01-31 13:50:07,421 1680 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database idomysbd because of modules to install/upgrade/remove.
2018-01-31 13:50:14,310 1680 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:14] "POST /longpolling/poll HTTP/1.1" 200 -
2018-01-31 13:50:16,071 1680 INFO ? odoo.service.server: Initiating shutdown
2018-01-31 13:50:16,071 1680 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
2018-01-31 13:50:19,707 7660 INFO ? odoo: Odoo version 11.0-20180105
2018-01-31 13:50:19,708 7660 INFO ? odoo: Using configuration file at C:\Program Files (x86)\Odoo 11.0\server\odoo.conf
2018-01-31 13:50:19,708 7660 INFO ? odoo: addons paths: ['C:\\Users\\Idomys\\AppData\\Local\\OpenERP S.A.\\Odoo\\addons\\11.0', 'C:\\Program Files (x86)\\Odoo 11.0\\server\\odoo\\addons']
2018-01-31 13:50:19,709 7660 INFO ? odoo: database: openpg@localhost:5432
2018-01-31 13:50:19,734 7660 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
2018-01-31 13:50:20,026 7660 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files (x86)\Odoo 11.0\thirdparty\wkhtmltopdf.exe
2018-01-31 13:50:24,363 7660 INFO ? odoo.http: HTTP Configuring static files
2018-01-31 13:50:24,449 7660 INFO idomysbd odoo.modules.loading: loading 1 modules...
2018-01-31 13:50:24,475 7660 INFO idomysbd odoo.modules.loading: 1 modules loaded in 0.03s, 0 queries
2018-01-31 13:50:24,581 7660 INFO idomysbd odoo.modules.loading: loading 46 modules...
2018-01-31 13:50:25,012 7660 INFO idomysbd odoo.modules.loading: 46 modules loaded in 0.43s, 0 queries
2018-01-31 13:50:25,875 7660 INFO idomysbd odoo.modules.loading: Modules loaded.
2018-01-31 13:50:25,885 7660 INFO idomysbd odoo.addons.base.ir.ir_http: Generating routing map
2018-01-31 13:50:28,299 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:28] "GET /web?debug=1 HTTP/1.1" 200 -
2018-01-31 13:50:28,629 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:28] "GET /web/webclient/qweb?mods=web,base,bus,web_tour,mail,product,portal,web_planner,project,sales_team,account,sale,account_invoicing,sale_management,web_editor,website,account_bank_statement_import,auth_signup,base_import,contacts,document,iap,l10n_fr,payment,payment_transfer,web_diagram,web_kanban_gauge,web_settings_dashboard,website_mail,website_quote,website_theme_install HTTP/1.1" 200 -
2018-01-31 13:50:28,631 7660 INFO ? werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:28] "GET /web/static/src/img/favicon.ico HTTP/1.1" 200 -
2018-01-31 13:50:28,650 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:28] "POST /web/dataset/call HTTP/1.1" 200 -
2018-01-31 13:50:29,031 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:29] "POST /web/webclient/translations HTTP/1.1" 200 -
2018-01-31 13:50:29,241 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:29] "GET /web/image?model=res.users&field=image_small&id=1 HTTP/1.1" 304 -
2018-01-31 13:50:29,279 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:29] "POST /mail/client_action HTTP/1.1" 200 -
2018-01-31 13:50:29,281 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:29] "POST /web/dataset/call_kw/res.users/check_access_rights HTTP/1.1" 200 -
2018-01-31 13:50:29,281 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:29] "POST /web/dataset/call_kw/ir.model.data/xmlid_to_res_id HTTP/1.1" 200 -
2018-01-31 13:50:29,282 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:29] "POST /web/dataset/call_kw/res.users/has_group HTTP/1.1" 200 -
2018-01-31 13:50:29,283 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:29] "POST /web/dataset/call_kw/ir.ui.view/check_access_rights HTTP/1.1" 200 -
2018-01-31 13:50:29,289 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:29] "POST /web/dataset/call_kw/res.users/activity_user_count HTTP/1.1" 200 -
2018-01-31 13:50:29,348 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:29] "POST /web/dataset/call_kw/web.planner/search_read HTTP/1.1" 200 -
2018-01-31 13:50:29,413 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:29] "POST /web/action/load HTTP/1.1" 200 -
2018-01-31 13:50:29,615 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:29] "POST /web/dataset/call_kw/ir.module.module/load_views HTTP/1.1" 200 -
2018-01-31 13:50:29,723 7660 WARNING idomysbd odoo.modules.module: module auto_backup: module not found
2018-01-31 13:50:29,726 7660 WARNING idomysbd odoo.modules.module: module auto_backup: module not found
2018-01-31 13:50:29,888 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:29] "POST /web/dataset/call_kw/ir.module.module/read HTTP/1.1" 200 -
2018-01-31 13:50:29,912 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:29] "POST /web/dataset/call_kw/ir.module.module.dependency/read HTTP/1.1" 200 -
2018-01-31 13:50:29,954 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:29] "POST /web/dataset/call_kw/ir.module.category/name_search HTTP/1.1" 200 -
2018-01-31 13:50:29,981 7660 INFO ? werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:29] "GET /web/static/src/img/placeholder.png HTTP/1.1" 200 -
2018-01-31 13:50:30,055 7660 INFO ? werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:30] "GET /base/static/src/css/description.css HTTP/1.1" 200 -
2018-01-31 13:50:30,058 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:30] "POST /web/dataset/call_kw/ir.attachment/search_read HTTP/1.1" 200 -
2018-01-31 13:50:30,145 7660 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres
2018-01-31 13:50:33,082 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:33] "POST /web/action/load HTTP/1.1" 200 -
2018-01-31 13:50:33,135 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:33] "POST /web_settings_dashboard/data HTTP/1.1" 200 -
2018-01-31 13:50:33,162 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:33] "POST /web/dataset/call_kw HTTP/1.1" 200 -
2018-01-31 13:50:33,208 7660 INFO idomysbd werkzeug: 192.168.1.64 - - [31/Jan/2018 13:50:33] "POST /web/dataset/call_kw/web.planner/search_read HTTP/1.1" 200 -

I think i've put too many lines from log but all we need is here, it tell me that module is not found but i can see him in applications list.

**Comment by bouet** [comment]
2018-01-31 13:50:29,726 7660 WARNING idomysbd odoo.modules.module: module auto_backup: module not found

Ok i've changed the foler where was the "auto-backup" folder, before i had copy it in "C:\Program Files (x86)\Odoo 11.0\server\addons"

And now i put it in "C:\Program Files (x86)\Odoo 11.0\server\odoo\addons"

But i got this error:
Error:

Odoo server error

Exception: Unable to load auto_backup module failed: auto_backup \ security / ir.model.access.csv file:

No record found for external id 'model_db_backup' in 'Subject' field

Missing value for the 'Object' champion (model_id)

No record found for external id 'model_db_backup' in 'Subject' field

Missing value for the 'Object' champion (model_id)

I've looked about the ir.model.access.cvs file but don't understand what is missing ?
Do i need to create an other database called "model_db_backup" ?

**Comment by bouet** [comment]
@Yenthe666 
I've followed this: https://github.com/Yenthe666/auto_backup/issues/65
But before it i had installed manually with command "pip install" all the "requirements.txt" in Odoo folder: 
Babel==2.3.4
decorator==4.0.10
docutils==0.12
ebaysdk==2.1.5
feedparser==5.2.1
gevent==1.1.2
greenlet==0.4.10
html2text==2016.9.19
Jinja2==2.8
lxml==3.5.0
Mako==1.0.4
MarkupSafe==0.23
mock==2.0.0
num2words==0.5.4
ofxparse==0.16
passlib==1.6.5
Pillow==3.4.1
psutil==4.3.1
psycopg2==2.7.3.1
pydot==1.2.3
pyldap==2.4.28
pyparsing==2.1.10
PyPDF2==1.26.0
pyserial==3.1.1
python-dateutil==2.5.3
pytz==2016.7
pyusb==1.0.0
PyYAML==3.12
qrcode==5.3
reportlab==3.3.0
requests==2.11.1
six==1.10.0
suds-jurko==0.6
vatnumber==1.2
vobject==0.9.3
Werkzeug==0.11.11
XlsxWriter==0.9.3
xlwt==1.3.*
xlrd==1.0.0
Then i did an "easy_install pysftp" but i still get the same error.
![easyinstall](https://user-images.githubusercontent.com/25053359/35631989-ae138faa-06a5-11e8-8c2b-fd8c671e5c51.PNG)

![odooerrorserver](https://user-images.githubusercontent.com/25053359/35632049-da9bb8ea-06a5-11e8-83ea-39c4055a1424.PNG)

**Comment by Yenthe666** [comment]
I'm closing this one off as honestly my intention was not even to support Windows, just Linux and 99% of Odoo's run on that. It really looks like a combination of misdeployment and configuration.

**Comment by poka-IT** [comment]
I have the exact same problem on Debian 9...

```
Exception: Impossible de charger le module auto_backup échec : fichier auto_backup/security/ir.model.access.csv :
Aucun enregistrement trouvé pour id externe 'model_db_backup' dans le champ 'Object'
Valeur requise manquante pour le champ 'Object' (model_id)
Aucun enregistrement trouvé pour id externe 'model_db_backup' dans le champ 'Object'
Valeur requise manquante pour le champ 'Object' (model_id)
```
