### ISSUE TITLE
Installation error on Odoo 11

### ISSUE THREAD

**Issue by rwngallego** [Yenthe666/auto_backup#92]
It's not possible to get it work on Odoo 11 (11.0-20171218):

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/module/module.py", line 539, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 782, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 829, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading auto_backup failed: file auto_backup/security/ir.model.access.csv could not be processed:
 No matching record found for external id 'model_db_backup' in field 'Object'
Missing required value for the field 'Object' (model_id)
No matching record found for external id 'model_db_backup' in field 'Object'
Missing required value for the field 'Object' (model_id)
```

**Comment by Yenthe666** [comment]
Hi @rwngallego,

Could you please change these two lines around at https://github.com/Yenthe666/auto_backup/blob/11.0/auto_backup/__manifest__.py#L32-L33, update your module, then try to install it again please?

**Comment by rwngallego** [comment]
@Yenthe666 done but now I get this error:

```
Odoo Server Error
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 967, in _validate_fields
    check(self)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 338, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 957, in postprocess_and_fields
    self.raise_view_error(_('Model not found: %(model)s') % dict(model=model), view_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 506, in raise_view_error
    raise ValueError(message)
ValueError: Model not found: db.backup

Error context:
View `db.backup.form`
[view_id: 1286, xml_id: n/a, model: db.backup, parent_id: n/a]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nModel not found: db.backup\n\nError context:\nView `db.backup.form`\n[view_id: 1286, xml_id: n/a, model: db.backup, parent_id: n/a]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/module/module.py", line 539, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 738, in parse
    self.parse(rec, mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Model not found: db.backup

Error context:
View `db.backup.form`
[view_id: 1286, xml_id: n/a, model: db.backup, parent_id: n/a]
None" while parsing /opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/auto_backup/views/backup_view.xml:3, near
<record id="view_backup_config_form" model="ir.ui.view">
            <field name="name">db.backup.form</field>
            <field name="model">db.backup</field>
            <field name="type">form</field>
            <field name="arch" type="xml">
                <form string="Back-up view">
                    <group col="4" colspan="4">
                        <separator col="2" string="Local backup configuration"/>
                    </group>
                    <group>
                        <field name="host" colspan="2"/>
                        <field name="name"/>
                        <field name="port"/>
                        <field name="backup_type"/>
                        <field name="folder"/>
                        <field name="autoremove"/>
                        <field name="days_to_keep" attrs="{'invisible': [('autoremove','=',False)]}"/>
                    </group>
                    <group col="4" colspan="4">
                        <separator col="2" string="SFTP"/>
                    </group>
                    <div style="width:50%;border-radius:10px;margin: 10px 0px;padding:15px 10px 15px 10px; background-repeat: no-repeat;background-position: 10px center;color: #9F6000;background-color: #FEEFB3;" attrs="{'invisible': [('sftp_write','=',False)]}">
                        <b>Warning:</b>
                        Use SFTP with caution! This writes files to external servers under the path you specify.
                    </div>
                    <group>
                        <field name="sftp_write"/>
                        <field name="sftp_host" attrs="{'invisible':[('sftp_write', '=', False)],'required':[('sftp_write', '=', True)]}"/>
                        <field name="sftp_port" attrs="{'invisible':[('sftp_write', '=', False)],'required':[('sftp_write', '=', True)]}"/>
                        <field name="sftp_user" attrs="{'invisible':[('sftp_write', '=', False)], 'required':[('sftp_write', '=', True)]}"/>
                        <field name="sftp_password" attrs="{'invisible':[('sftp_write', '=', False)],'required': [('sftp_write', '=', True)]}" password="True"/>
                        <field name="sftp_path" attrs="{'invisible':[('sftp_write', '==', False)],'required':[('sftp_write', '==', True)]}" placeholder="For example: /odoo/backups/"/>
                        <field name="days_to_keep_sftp" attrs="{'invisible': [('sftp_write', '=', False)], 'required': [('sftp_write', '=', True)]}"/>
                        <field name="send_mail_sftp_fail" attrs="{'invisible': [('sftp_write','=',False)]}"/>
                        <field name="email_to_notify" attrs="{'invisible':['|',('send_mail_sftp_fail', '==', False), ('sftp_write', '=', False)], 'required': [('send_mail_sftp_fail', '=', True)]}"/>
                        <button name="test_sftp_connection" type="object" attrs="{'invisible': [('sftp_write','=',False)]}" string="Test SFTP Connection"/>
                    </group>
                    <separator string="Help" colspan="2"/>
                    <div>
                        This configures the scheduler for automatic backup of the given database running on given host
                        at given port on regular intervals.
                        <br/>
                        Automatic backups of the database can be scheduled as follows:
                        <ol>
                            <li>
                                Go to Settings / Technical / Automation / Scheduled Actions.
                            </li>
                            <li>
                                Search the action named 'Backup scheduler'.
                            </li>
                            <li>
                                Set the scheduler to active and fill in how often you want backups generated.
                            </li>
                        </ol>
                        <p style="font-size:18px;">
                            Need more help?
                            <a href="https://github.com/Yenthe666/auto_backup">Contact me!</a>
                        </p>
                    </div>
                </form>
            </field>
        </record>
```

**Comment by Yenthe666** [comment]
Hmm, the odd thing is that a few people in the past have mentioned this issue too but nobody was ever able to figure it out and neither was I..
I literally can't find a way to reproduce this. 😕

**Comment by rwngallego** [comment]
If you want to reproduce it, you can mount an image of Odoo 11 using Bitnami and then install your module: 
https://bitnami.com/stack/odoo/virtual-machine

**Comment by Yenthe666** [comment]
@rwngallego give me some time to try that, a bit busy at the moment.
Just send me a reminder if you had no response in 5 days.

**Comment by simonitfi** [comment]
#93 fixed this with me.

**Comment by Yenthe666** [comment]
@simosuu thanks for the fix! On which OS did you test this?

**Comment by simonitfi** [comment]
Debian 9

**Comment by Yenthe666** [comment]
Thanks. I'll try to test this as soon as possible on Ubuntu 16.04 too.
@rwngallego could you please try this on your bitnami too?

**Comment by rwngallego** [comment]
I've checked this one on a newer Odoo version and I remember it still had errors. I cannot give more feedback at the moment but if it still happens reopen this issue.

**Comment by docilweb** [comment]
I cant't install on Odoo 11.0-20180425. I change code with #93 but the problem persist:

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 782, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 829, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Fallo en la carga del módulo auto_backup: no se pudo procesar el archivo auto_backup/security/ir.model.access.csv:
No se han encontrado registros coincidentes para id. externo 'db_backup.model_db_backup' en el campo 'Object'
Falta el valor requerido para el campo 'Object' (model_id)
No se han encontrado registros coincidentes para id. externo 'db_backup.model_db_backup' en el campo 'Object'
Falta el valor requerido para el campo 'Object' (model_id)`

**Comment by rubybinhvn** [comment]
Lỗi:
Odoo Server Error

Traceback (most recent call last):
  File "/bhtvn/bhtvn-server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/bhtvn/bhtvn-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/bhtvn/bhtvn-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/bhtvn/bhtvn-server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/bhtvn/bhtvn-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/bhtvn/bhtvn-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/bhtvn/bhtvn-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/bhtvn/bhtvn-server/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/bhtvn/bhtvn-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/bhtvn/bhtvn-server/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/bhtvn/bhtvn-server/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/bhtvn/bhtvn-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/bhtvn/bhtvn-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/bhtvn/bhtvn-server/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/bhtvn/bhtvn-server/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/bhtvn/bhtvn-server/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/bhtvn/bhtvn-server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/bhtvn/bhtvn-server/odoo/modules/loading.py", line 371, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/bhtvn/bhtvn-server/odoo/modules/loading.py", line 265, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/bhtvn/bhtvn-server/odoo/modules/loading.py", line 172, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/bhtvn/bhtvn-server/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/bhtvn/bhtvn-server/odoo/tools/convert.py", line 785, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/bhtvn/bhtvn-server/odoo/tools/convert.py", line 832, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading auto_backup failed: file auto_backup/security/ir.model.access.csv could not be processed:
 No matching record found for external id 'model_db_backup' in field 'Object'
Missing required value for the field 'Object' (model_id)
No matching record found for external id 'model_db_backup' in field 'Object'
Missing required value for the field 'Object' (model_id)

**Comment by 3mrdev** [comment]
@docilweb @rubybinhvn Solution is restarting your odoo-server after installing pysftp see #166
