### ISSUE TITLE
AttributeError: 'module' object has no attribute 'add_metaclass'

### ISSUE THREAD

**Issue by Bowsertje** [Yenthe666/auto_backup#95]
I am getting this error after installing psyftp and then uploading the auto_backup module to my custom addon dir.

Traceback (most recent call last):
  File "/opt/odoo-acc/odoo-server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo-acc/odoo-server/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo-acc/odoo-server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo-acc/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo-acc/odoo-server/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo-acc/odoo-server/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo-acc/odoo-server/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo-acc/odoo-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo-acc/odoo-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo-acc/odoo-server/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo-acc/odoo-server/openerp/api.py", line 427, in old_api
    result = new_api(recs, *args, **kwargs)
  File "/opt/odoo-acc/odoo-server/openerp/api.py", line 431, in new_api
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo-acc/odoo-server/openerp/addons/base/module/wizard/base_module_update.py", line 15, in update_module
    self.updated, self.added = self.env['ir.module.module'].update_list()
  File "/opt/odoo-acc/odoo-server/openerp/api.py", line 254, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo-acc/odoo-server/openerp/api.py", line 496, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo-acc/odoo-server/openerp/addons/base/module/module.py", line 651, in update_list
    handler.load_addons()
  File "/opt/odoo-acc/odoo-server/openerp/http.py", line 1310, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/opt/odoo-acc/odoo-server/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo-acc/custom/addons/auto_backup/__init__.py", line 23, in <module>
    import backup_scheduler
  File "/opt/odoo-acc/custom/addons/auto_backup/backup_scheduler.py", line 31, in <module>
    import pysftp
  File "/usr/local/lib/python2.7/dist-packages/pysftp/__init__.py", line 12, in <module>
    import paramiko
  File "/usr/local/lib/python2.7/dist-packages/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 34, in <module>
    from cryptography.hazmat.primitives.ciphers import algorithms, Cipher, modes
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/ciphers/__init__.py", line 7, in <module>
    from cryptography.hazmat.primitives.ciphers.base import (
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/ciphers/base.py", line 16, in <module>
    from cryptography.hazmat.backends.interfaces import CipherBackend
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/interfaces.py", line 12, in <module>
    @six.add_metaclass(abc.ABCMeta)
AttributeError: 'module' object has no attribute 'add_metaclass'

**Comment by Yenthe666** [comment]
@Bowsertje the error is coming from an external depencency (`cryptography`) so there is not much I can do about that..
Please make a bug report about that traceback there (bottom part of the traceback, not the Odoo part)
