### ISSUE TITLE
Auto_backup on Odoo 8

### ISSUE THREAD

**Issue by jcchoquet** [Yenthe666/auto_backup#99]
Hello,
I have installed your module since 1 year on Odoo 8 it worked nice, but since 2 weeks i have this error:

2018-05-15 17:59:22,684 2270 ERROR LDS_Location openerp.addons.base.ir.ir_cron: Call of self.pool.get('db.backup').schedule_backup(cr, uid, *()) failed in Job 7
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_cron.py", line 138, in _callback
    getattr(model, method_name)(cr, uid, *args)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/addons/auto_backup/backup_scheduler.py", line 158, in schedule_backup
    _logger.notifyChannel('backup', netsvc.LOG_INFO, "Couldn't backup database %s. Bad database administrator password for server running at http://%s:%s" %(rec.name, rec.host, rec.port))
AttributeError: 'Logger' object has no attribute 'notifyChannel'

I don't change anything on Odoo or on Server...

**Comment by Yenthe666** [comment]
Hi @jcchoquet,

Odd. Replace `_logger.notifyChannel ` with `_logger.debug` and it'll work.

Regards,
Yenthe

**Comment by jcchoquet** [comment]
OK I will test it. Thanks!
